### ISSUE TITLE
Legacy node query crashed the node with 500 error

### ISSUE THREAD

**Issue by svenger87** [iotaledger/hornet#1063]
```Apr 29 10:25:48 svenger87 hornet-mainnet[765010]: req(qu/pe/proc/lat): 00000/00000/00000/0000ms, reqQMs: 0, processor: 00000, CMI/LMI: 6800/6800, MPS (in/new/out): 00058/00013/00085, Tips (non-/semi-lazy): 79/0
Apr 29 10:25:49 svenger87 hornet-mainnet[765010]: req(qu/pe/proc/lat): 00000/00000/00000/0000ms, reqQMs: 0, processor: 00000, CMI/LMI: 6800/6800, MPS (in/new/out): 00069/00013/00084, Tips (non-/semi-lazy): 74/0
Apr 29 10:25:50 svenger87 hornet-mainnet[765010]: req(qu/pe/proc/lat): 00000/00000/00000/0000ms, reqQMs: 0, processor: 00000, CMI/LMI: 6800/6800, MPS (in/new/out): 00042/00008/00053, Tips (non-/semi-lazy): 71/0
Apr 29 10:25:51 svenger87 hornet-mainnet[765010]: req(qu/pe/proc/lat): 00000/00000/00000/0000ms, reqQMs: 0, processor: 00000, CMI/LMI: 6800/6800, MPS (in/new/out): 00073/00016/00104, Tips (non-/semi-lazy): 68/0
Apr 29 10:25:52 svenger87 hornet-mainnet[765010]: req(qu/pe/proc/lat): 00000/00000/00000/0000ms, reqQMs: 0, processor: 00000, CMI/LMI: 6800/6800, MPS (in/new/out): 00081/00017/00112, Tips (non-/semi-lazy): 74/0
Apr 29 10:25:53 svenger87 hornet-mainnet[765010]: req(qu/pe/proc/lat): 00000/00000/00000/0000ms, reqQMs: 0, processor: 00000, CMI/LMI: 6800/6800, MPS (in/new/out): 00081/00017/00112, Tips (non-/semi-lazy): 80/0
Apr 29 10:25:54 svenger87 hornet-mainnet[765010]: req(qu/pe/proc/lat): 00000/00000/00000/0000ms, reqQMs: 0, processor: 00000, CMI/LMI: 6800/6800, MPS (in/new/out): 00091/00018/00115, Tips (non-/semi-lazy): 82/0
Apr 29 10:25:55 svenger87 hornet-mainnet[765010]: req(qu/pe/proc/lat): 00000/00000/00000/0000ms, reqQMs: 0, processor: 00000, CMI/LMI: 6800/6800, MPS (in/new/out): 00091/00018/00115, Tips (non-/semi-lazy): 93/0
Apr 29 10:25:56 svenger87 hornet-mainnet[765010]: req(qu/pe/proc/lat): 00000/00000/00000/0000ms, reqQMs: 0, processor: 00000, CMI/LMI: 6800/6800, MPS (in/new/out): 00096/00020/00127, Tips (non-/semi-lazy): 87/0
Apr 29 10:25:57 svenger87 hornet-mainnet[765010]: req(qu/pe/proc/lat): 00000/00000/00000/0000ms, reqQMs: 0, processor: 00000, CMI/LMI: 6800/6800, MPS (in/new/out): 00061/00012/00078, Tips (non-/semi-lazy): 89/0
Apr 29 10:25:58 svenger87 hornet-mainnet[765010]: 2021-04-29T10:25:58+02:00        INFO        Tangle        Valid milestone detected! Index: 6801
Apr 29 10:25:58 svenger87 hornet-mainnet[765010]: 2021-04-29T10:25:58+02:00        INFO        Tangle        Run solidity check for Milestone (6801)...
Apr 29 10:25:58 svenger87 hornet-mainnet[765010]: 2021-04-29T10:25:58+02:00        INFO        Tangle        Solidifier finished: msgs: 1, collect: 0s, solidity 0s, propagation: 1ms, total: 1ms
Apr 29 10:25:58 svenger87 hornet-mainnet[765010]: 2021-04-29T10:25:58+02:00        PANIC        Tangle        unable to query migrated funds from legacy node for receipt validation: API call failed: error message: internal error: key not found;http status code: 500;
Apr 29 10:25:58 svenger87 hornet-mainnet[765010]: github.com/gohornet/hornet/pkg/tangle.(*Tangle).solidifyMilestone
Apr 29 10:25:58 svenger87 hornet-mainnet[765010]:         /__w/hornet/hornet/pkg/tangle/solidifier.go:323
Apr 29 10:25:58 svenger87 hornet-mainnet[765010]: github.com/gohornet/hornet/pkg/tangle.(*Tangle).ConfigureTangleProcessor.func4
Apr 29 10:25:58 svenger87 hornet-mainnet[765010]:         /__w/hornet/hornet/pkg/tangle/tangle_processor.go:37
Apr 29 10:25:58 svenger87 hornet-mainnet[765010]: github.com/iotaledger/hive.go/workerpool.(*WorkerPool).startWorkers.func1
Apr 29 10:25:58 svenger87 hornet-mainnet[765010]:         /github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20210423125659-4446146a4c6b/workerpool/workerpool.go:158
Apr 29 10:25:58 svenger87 hornet-mainnet[765010]: panic: unable to query migrated funds from legacy node for receipt validation: API call failed: error message: internal error: key not found;http status code: 500;
Apr 29 10:25:58 svenger87 hornet-mainnet[765010]: goroutine 470 [running]:
Apr 29 10:25:58 svenger87 hornet-mainnet[765010]: go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc000228540, 0x0, 0x0, 0x0)
Apr 29 10:25:58 svenger87 hornet-mainnet[765010]:         /github/home/go/pkg/mod/go.uber.org/zap@v1.16.0/zapcore/entry.go:234 +0x58d
Apr 29 10:25:58 svenger87 hornet-mainnet[765010]: go.uber.org/zap.(*SugaredLogger).log(0xc00018c3d0, 0xc000081004, 0x0, 0x0, 0xc003817c00, 0x1, 0x1, 0x0, 0x0, 0x0)
Apr 29 10:25:58 svenger87 hornet-mainnet[765010]:         /github/home/go/pkg/mod/go.uber.org/zap@v1.16.0/sugar.go:234 +0xf6
Apr 29 10:25:58 svenger87 hornet-mainnet[765010]: go.uber.org/zap.(*SugaredLogger).Panic(...)
Apr 29 10:25:58 svenger87 hornet-mainnet[765010]:         /github/home/go/pkg/mod/go.uber.org/zap@v1.16.0/sugar.go:123
Apr 29 10:25:58 svenger87 hornet-mainnet[765010]: github.com/gohornet/hornet/pkg/tangle.(*Tangle).solidifyMilestone(0xc000287500, 0x1a91)
Apr 29 10:25:58 svenger87 hornet-mainnet[765010]:         /__w/hornet/hornet/pkg/tangle/solidifier.go:323 +0xd45
Apr 29 10:25:58 svenger87 hornet-mainnet[765010]: github.com/gohornet/hornet/pkg/tangle.(*Tangle).ConfigureTangleProcessor.func4(0xc000723c80, 0x2, 0x2, 0xc004249080)
Apr 29 10:25:58 svenger87 hornet-mainnet[765010]:         /__w/hornet/hornet/pkg/tangle/tangle_processor.go:37 +0x7f
Apr 29 10:25:58 svenger87 hornet-mainnet[765010]: github.com/iotaledger/hive.go/workerpool.(*WorkerPool).startWorkers.func1(0xc002a92690)
Apr 29 10:25:58 svenger87 hornet-mainnet[765010]:         /github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20210423125659-4446146a4c6b/workerpool/workerpool.go:158 +0x1a3
Apr 29 10:25:58 svenger87 hornet-mainnet[765010]: created by github.com/iotaledger/hive.go/workerpool.(*WorkerPool).startWorkers
Apr 29 10:25:58 svenger87 hornet-mainnet[765010]:         /github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20210423125659-4446146a4c6b/workerpool/workerpool.go:134 +0x5f
Apr 29 10:25:58 svenger87 systemd[1]: hornet-mainnet.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 29 10:25:58 svenger87 systemd[1]: hornet-mainnet.service: Failed with result 'exit-code'.
Apr 29 10:27:38 svenger87 systemd[1]: hornet-mainnet.service: Scheduled restart job, restart counter is at 1.
Apr 29 10:27:38 svenger87 systemd[1]: Stopped Hornet Mainnet.```

**Comment by svenger87** [comment]
Database revalidation failed.

```
Apr 29 10:54:36 svenger87 hornet-mainnet[799308]: panic: Database revalidation failed! Please delete the database folder and start with a new snapshot. snapshot index does not fit the snapshot ledger index
Apr 29 10:54:36 svenger87 hornet-mainnet[799308]: goroutine 1 [running]:
Apr 29 10:54:36 svenger87 hornet-mainnet[799308]: go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc000240480, 0x0, 0x0, 0x0)
Apr 29 10:54:36 svenger87 hornet-mainnet[799308]:         /github/home/go/pkg/mod/go.uber.org/zap@v1.16.0/zapcore/entry.go:234 +0x58d
Apr 29 10:54:36 svenger87 hornet-mainnet[799308]: go.uber.org/zap.(*SugaredLogger).log(0xc000010e60, 0xc00000e404, 0x1f1c068, 0x5, 0xc0000b3d50, 0x2, 0x2, 0x0, 0x0, 0x0)
Apr 29 10:54:36 svenger87 hornet-mainnet[799308]:         /github/home/go/pkg/mod/go.uber.org/zap@v1.16.0/sugar.go:234 +0xf6
Apr 29 10:54:36 svenger87 hornet-mainnet[799308]: go.uber.org/zap.(*SugaredLogger).Panicf(...)
Apr 29 10:54:36 svenger87 hornet-mainnet[799308]:         /github/home/go/pkg/mod/go.uber.org/zap@v1.16.0/sugar.go:159
Apr 29 10:54:36 svenger87 hornet-mainnet[799308]: github.com/gohornet/hornet/core/tangle.configure()
Apr 29 10:54:36 svenger87 hornet-mainnet[799308]:         /__w/hornet/hornet/core/tangle/core.go:162 +0x326
Apr 29 10:54:36 svenger87 hornet-mainnet[799308]: github.com/gohornet/hornet/pkg/node.(*Node).configure.func1(0xc00008cd70, 0x1c5c701)
Apr 29 10:54:36 svenger87 hornet-mainnet[799308]:         /__w/hornet/hornet/pkg/node/node.go:212 +0xdd
Apr 29 10:54:36 svenger87 hornet-mainnet[799308]: github.com/gohornet/hornet/pkg/node.forEachCorePlugin(0xc00012cc00, 0x9, 0x10, 0xc0000b3e40)
Apr 29 10:54:36 svenger87 hornet-mainnet[799308]:         /__w/hornet/hornet/pkg/node/node.go:320 +0x51
Apr 29 10:54:36 svenger87 hornet-mainnet[799308]: github.com/gohornet/hornet/pkg/node.(*Node).ForEachCorePlugin(...)
Apr 29 10:54:36 svenger87 hornet-mainnet[799308]:         /__w/hornet/hornet/pkg/node/node.go:328
Apr 29 10:54:36 svenger87 hornet-mainnet[799308]: github.com/gohornet/hornet/pkg/node.(*Node).configure(0xc000029a40)
Apr 29 10:54:36 svenger87 hornet-mainnet[799308]:         /__w/hornet/hornet/pkg/node/node.go:210 +0x7c
Apr 29 10:54:36 svenger87 hornet-mainnet[799308]: github.com/gohornet/hornet/pkg/node.New(0xc00080ff60, 0x3, 0x3, 0x1d3ba40)
Apr 29 10:54:36 svenger87 hornet-mainnet[799308]:         /__w/hornet/hornet/pkg/node/node.go:49 +0x248
Apr 29 10:54:36 svenger87 hornet-mainnet[799308]: github.com/gohornet/hornet/pkg/node.Run(0xc00080ff60, 0x3, 0x3, 0xc0001b7a40)
Apr 29 10:54:36 svenger87 hornet-mainnet[799308]:         /__w/hornet/hornet/pkg/node/node.go:62 +0x3f
Apr 29 10:54:36 svenger87 hornet-mainnet[799308]: main.main()
Apr 29 10:54:36 svenger87 hornet-mainnet[799308]:         /__w/hornet/hornet/main.go:33 +0x334
Apr 29 10:54:36 svenger87 systemd[1]: hornet-mainnet.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 29 10:54:36 svenger87 systemd[1]: hornet-mainnet.service: Failed with result 'exit-code'.
```

**Comment by svenger87** [comment]
"IgnoreSoftErrors": true set to config.json
