### ISSUE TITLE
Segfault while syncing

### ISSUE THREAD

**Issue by coinwalletdev** [iotaledger/hornet#17]
**Describe the bug**
While syncing a fresh install of hornet, it died with this stacktrace:

```
May 10 11:43:22 hornet[1221]: panic: runtime error: invalid memory address or nil pointer dereference
May 10 11:43:22 hornet[1221]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0xf6703a]
May 10 11:43:22 hornet[1221]: goroutine 419 [running]:
May 10 11:43:22 hornet[1221]: github.com/gohornet/hornet/pkg/snapshot.(*Snapshot).optimalSnapshotType(0xc00011c340, 0x19107)
May 10 11:43:22 hornet[1221]:         /__w/hornet/hornet/pkg/snapshot/snapshot.go:1042 +0x11a
May 10 11:43:22 hornet[1221]: github.com/gohornet/hornet/pkg/snapshot.(*Snapshot).HandleNewConfirmedMilestoneEvent(0xc00011c340, 0xc000019107, 0xc0023eba40)
May 10 11:43:22 hornet[1221]:         /__w/hornet/hornet/pkg/snapshot/snapshot.go:1073 +0x20c
May 10 11:43:22 hornet[1221]: github.com/gohornet/hornet/core/snapshot.run.func2(0xc0023eba40)
May 10 11:43:22 hornet[1221]:         /__w/hornet/hornet/core/snapshot/core.go:192 +0x150
May 10 11:43:22 hornet[1221]: github.com/iotaledger/hive.go/daemon.(*OrderedDaemon).runBackgroundWorker.func1(0xc00003e200, 0x1f39ecd, 0x9, 0xc0024e2cf0, 0xc0006ef320, 0xc00380b310)
May 10 11:43:22 hornet[1221]:         /github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20210423125659-4446146a4c6b/daemon/daemon.go:146 +0x51
May 10 11:43:22 hornet[1221]: created by github.com/iotaledger/hive.go/daemon.(*OrderedDaemon).runBackgroundWorker
May 10 11:43:22 hornet[1221]:         /github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20210423125659-4446146a4c6b/daemon/daemon.go:142 +0x105
May 10 11:43:22 systemd[1]: hornet.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 10 11:43:22 systemd[1]: hornet.service: Failed with result 'exit-code'.
May 10 11:43:22 systemd[1]: hornet.service: Scheduled restart job, restart counter is at 1.
```

**To Reproduce**
Not sure. 
I was missing some write permissions on the hornet data folder, so you might double check you're not trying to write somewhere without having the write permission.

**Environment information:**
 - HORNET version 1.0.1

**Comment by muXxer** [comment]
Thank you for the issue report.

Sorry that I didn't see it because the original upstream repository is [here](https://github.com/gohornet/hornet/).
Should be fixed by the latest commit in the develop branch.
