### ISSUE TITLE
panic: Could not open new DB: During db.vlog.open: Value log truncate required to run DB. This might result in data loss

### ISSUE THREAD

**Issue by yillkid** [iotaledger/hornet#200]
**Describe the bug**
HORNET fails and exits in [hornet-playbook](https://github.com/nuriel77/hornet-playbook) launch script after the system recovers from a **no space left on device** situation. 

**To Reproduce**
$ sudo journalctl  -u hornet

```
Feb 24 04:52:55 hornet docker[2414]: 2020-02-24T04:52:55Z        INFO        Node        Using profile '1gb'
Feb 24 04:52:55 hornet docker[2414]: 2020-02-24T04:52:55Z        INFO        Node        Loading plugins ...
Feb 24 04:52:55 hornet docker[2414]: 2020-02-24T04:52:55Z        INFO        Node        Loading Plugin: CLI ... done
Feb 24 04:52:55 hornet docker[2414]: 2020-02-24T04:52:55Z        INFO        Node        Loading Plugin: Graceful Shutdown ... done
Feb 24 04:52:55 hornet docker[2414]: 2020-02-24T04:52:55Z        INFO        Gossip        added neighbor node.deviceproof.org:15600 into reconnect pool for the first time
Feb 24 04:52:55 hornet docker[2414]: 2020-02-24T04:52:55Z        INFO        Gossip        added neighbor node1.puyuma.org:15600 into reconnect pool for the first time
Feb 24 04:52:55 hornet docker[2414]: 2020-02-24T04:52:55Z        INFO        Gossip        added neighbor node10.puyuma.org:15600 into reconnect pool for the first time
Feb 24 04:52:55 hornet docker[2414]: 2020-02-24T04:52:55Z        INFO        Gossip        Configuring packetProcessorWorkerPool with 512 workers
Feb 24 04:52:55 hornet docker[2414]: 2020-02-24T04:52:55Z        INFO        Node        Loading Plugin: Gossip ... done
Feb 24 04:52:56 hornet docker[2414]: panic: Could not open new DB: During db.vlog.open: Value log truncate required to run DB. This might result in data loss
Feb 24 04:52:56 hornet docker[2414]: goroutine 1 [running]:
Feb 24 04:52:56 hornet docker[2414]: github.com/gohornet/hornet/packages/database.GetBadgerInstance.func1()
Feb 24 04:52:56 hornet docker[2414]:         /__w/hornet/hornet/packages/database/badger_instance.go:67 +0x74b
Feb 24 04:52:56 hornet docker[2414]: sync.(*Once).doSlow(0x1f7bd00, 0x1707198)
Feb 24 04:52:56 hornet docker[2414]:         /usr/local/go/src/sync/once.go:66 +0xe3
Feb 24 04:52:56 hornet docker[2414]: sync.(*Once).Do(...)
Feb 24 04:52:56 hornet docker[2414]:         /usr/local/go/src/sync/once.go:57
Feb 24 04:52:56 hornet docker[2414]: github.com/gohornet/hornet/packages/database.GetBadgerInstance(0xc000168900)
Feb 24 04:52:56 hornet docker[2414]:         /__w/hornet/hornet/packages/database/badger_instance.go:29 +0x59
Feb 24 04:52:56 hornet docker[2414]: github.com/gohornet/hornet/packages/model/tangle.configureHealthDatabase()
Feb 24 04:52:56 hornet docker[2414]:         /__w/hornet/hornet/packages/model/tangle/health_db.go:21 +0x26
Feb 24 04:52:56 hornet docker[2414]: github.com/gohornet/hornet/packages/model/tangle.ConfigureDatabases(0xc0003e09f4, 0x9, 0x1ef8a90)
Feb 24 04:52:56 hornet docker[2414]:         /__w/hornet/hornet/packages/model/tangle/tangle.go:10 +0x51
Feb 24 04:52:56 hornet docker[2414]: github.com/gohornet/hornet/plugins/tangle.configure(0xc000112740)
Feb 24 04:52:56 hornet docker[2414]:         /__w/hornet/hornet/plugins/tangle/plugin.go:41 +0x274
Feb 24 04:52:56 hornet docker[2414]: github.com/iotaledger/hive.go/node.pluginCaller(0xea61c0, 0x1707618, 0xc0000ee350, 0x1, 0x1)
Feb 24 04:52:56 hornet docker[2414]:         /go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200107205115-986a54f82a30/node/events.go:13 +0x62
Feb 24 04:52:56 hornet docker[2414]: github.com/iotaledger/hive.go/events.(*Event).Trigger(0xc00017c840, 0xc0000ee350, 0x1, 0x1)
Feb 24 04:52:56 hornet docker[2414]:         /go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200107205115-986a54f82a30/events/event.go:31 +0xdb
Feb 24 04:52:56 hornet docker[2414]: github.com/iotaledger/hive.go/node.(*Node).configure(0xc000033590, 0xc000478000, 0xe, 0xe)
Feb 24 04:52:56 hornet docker[2414]:         /go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200107205115-986a54f82a30/node/node.go:77 +0x102
Feb 24 04:52:56 hornet docker[2414]: github.com/iotaledger/hive.go/node.New(0xc000297f48, 0x1, 0x1, 0xf3c3c0)
Feb 24 04:52:56 hornet docker[2414]:         /go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200107205115-986a54f82a30/node/node.go:33 +0x124
Feb 24 04:52:56 hornet docker[2414]: github.com/iotaledger/hive.go/node.Run(0xc000297f48, 0x1, 0x1, 0xc00000e380)
Feb 24 04:52:56 hornet docker[2414]:         /go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200107205115-986a54f82a30/node/node.go:46 +0x3f
Feb 24 04:52:56 hornet docker[2414]: main.main()
Feb 24 04:52:56 hornet docker[2414]:         /__w/hornet/hornet/main.go:35 +0x22b
Feb 24 04:52:56 hornet systemd[1]: hornet.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 24 04:52:56 hornet systemd[1]: hornet.service: Failed with result 'exit-code'.
```

**Expected behavior**
Success to start the HORNET service

**Environment information:**
 - OS: Ubuntu 18.04
 - RAM: 2 GB
 - Cores: 4 Cores
 - Type: x86 VM of proxmox 
 - HORNET version:  v0.3.0

**Additional context**
none

**Comment by IoTMOD** [comment]
For HORNET-Playbook related issues please open an issue here:
https://github.com/nuriel77/hornet-playbook

To fix this issue please delete the mainnetdb folder (and cleanup your disk if necessary) and restart HORNET.

I'll close this issue because it's not related to HORNET but your disk space.
