### ISSUE TITLE
HORNET out of memory when reverting database state back to local snapshot

### ISSUE THREAD

**Issue by yillkid** [iotaledger/hornet#395]
**Describe the bug**
HORNET will  reverting database state back to local snapshot when it isn't shut down correctly, but a error message `out of memory` show on `0.4.0-rc8`.

**To Reproduce**
- Run 0.4.0-rc8
  - $ ./hornet -c config

**Expected behavior**
launch hornet

**Environment information:**
 - HORNET version
  - HORNET 0.4.0-rc8

- Operating system
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```

- Hardware
![image](https://user-images.githubusercontent.com/185872/79678373-72d62f00-822d-11ea-946c-2c665a095fc7.png)

**Full-log**
```
2020-04-19T02:49:24Z	WARN	Tangle	HORNET was not shut down correctly, the database may be corrupted. Starting revalidation...
2020-04-19T02:49:24Z	INFO	Tangle	reverting database state back to local snapshot 1379228...
fatal error: runtime: out of memory	

runtime stack:
runtime.throw(0x1151d4e, 0x16)
	/usr/local/go/src/runtime/panic.go:1114 +0x72
runtime.sysMap(0xc060000000, 0x4000000, 0x27f31b8)
	/usr/local/go/src/runtime/mem_linux.go:169 +0xc5
runtime.(*mheap).sysAlloc(0x27dc500, 0x400000, 0x27705e0, 0x0)
	/usr/local/go/src/runtime/malloc.go:715 +0x1cd
runtime.(*mheap).grow(0x27dc500, 0x1, 0x0)
	/usr/local/go/src/runtime/mheap.go:1286 +0x11c
runtime.(*mheap).allocSpan(0x27dc500, 0x1, 0xc00a420600, 0x27f31c8, 0x7f96245a15f8)
	/usr/local/go/src/runtime/mheap.go:1124 +0x6a0
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:871 +0x64
runtime.systemstack(0x0)
	/usr/local/go/src/runtime/asm_amd64.s:370 +0x66
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1041

goroutine 7230 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:330 fp=0xc00a427c08 sp=0xc00a427c00 pc=0x470a10
runtime.(*mheap).alloc(0x27dc500, 0x1, 0x7f95bd340106, 0x7f96245a15f8)
	/usr/local/go/src/runtime/mheap.go:865 +0x81 fp=0xc00a427c58 sp=0xc00a427c08 pc=0x431101
runtime.(*mcentral).grow(0x27ecad8, 0x0)
	/usr/local/go/src/runtime/mcentral.go:255 +0x79 fp=0xc00a427c98 sp=0xc00a427c58 pc=0x423689
runtime.(*mcentral).cacheSpan(0x27ecad8, 0x203017)
	/usr/local/go/src/runtime/mcentral.go:106 +0x2bc fp=0xc00a427ce0 sp=0xc00a427c98 pc=0x4231bc
runtime.(*mcache).refill(0x7f969ba877d0, 0x106)
	/usr/local/go/src/runtime/mcache.go:138 +0x85 fp=0xc00a427d00 sp=0xc00a427ce0 pc=0x422ca5
runtime.(*mcache).nextFree(0x7f969ba877d0, 0x6, 0x20, 0xf76740, 0x0)
	/usr/local/go/src/runtime/malloc.go:868 +0x87 fp=0xc00a427d38 sp=0xc00a427d00 pc=0x4178b7
runtime.mallocgc(0x20, 0xf951c0, 0xc01b40d601, 0xc01b40d6e0)
	/usr/local/go/src/runtime/malloc.go:1036 +0x793 fp=0xc00a427dd8 sp=0xc00a427d38 pc=0x4181f3
runtime.convTslice(0xc05f5c31c0, 0x31, 0x31, 0x31)
	/usr/local/go/src/runtime/iface.go:378 +0x5d fp=0xc00a427e08 sp=0xc00a427dd8 pc=0x415a5d
github.com/iotaledger/hive.go/objectstorage.(*ObjectStorage).deleteElementFromUnpartitionedCache(0xc009cfa090, 0xc05f5c31c0, 0x31, 0x31, 0x1)
	/github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200402214644-8da1ccad4605/objectstorage/object_storage.go:614 +0x177 fp=0xc00a427e80 sp=0xc00a427e08 pc=0x87fd87
github.com/iotaledger/hive.go/objectstorage.(*ObjectStorage).deleteElementFromCache(0xc009cfa090, 0xc05f5c31c0, 0x31, 0x31, 0x1)
	/github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200402214644-8da1ccad4605/objectstorage/object_storage.go:598 +0x92 fp=0xc00a427eb8 sp=0xc00a427e80 pc=0x87fbf2
github.com/iotaledger/hive.go/objectstorage.(*BatchedWriter).releaseObject(0xc000403890, 0xc05f5aee80)
	/github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200402214644-8da1ccad4605/objectstorage/batch_writer.go:114 +0x112 fp=0xc00a427f00 sp=0xc00a427eb8 pc=0x87b032
github.com/iotaledger/hive.go/objectstorage.(*BatchedWriter).runBatchWriter(0xc000403890)
	/github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200402214644-8da1ccad4605/objectstorage/batch_writer.go:154 +0x1b7 fp=0xc00a429fd8 sp=0xc00a427f00 pc=0x87b237
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc00a429fe0 sp=0xc00a429fd8 pc=0x472b21
created by github.com/iotaledger/hive.go/objectstorage.(*BatchedWriter).StartBatchWriter
	/github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200402214644-8da1ccad4605/objectstorage/batch_writer.go:43 +0x93

goroutine 1 [semacquire]:
sync.runtime_SemacquireMutex(0xc009cfa0c4, 0x27cbd01, 0x1)
	/usr/local/go/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc009cfa0c0)
	/usr/local/go/src/sync/mutex.go:138 +0xfc
sync.(*Mutex).Lock(...)
	/usr/local/go/src/sync/mutex.go:81
sync.(*RWMutex).Lock(0xc009cfa0c0)
	/usr/local/go/src/sync/rwmutex.go:98 +0x97
github.com/iotaledger/hive.go/objectstorage.(*ObjectStorage).accessNonPartitionedCache(0xc009cfa090, 0xc05ffafc00, 0x31, 0x31, 0x100000000000001, 0x0, 0x0)
	/github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200402214644-8da1ccad4605/objectstorage/object_storage.go:456 +0x15c
github.com/iotaledger/hive.go/objectstorage.(*ObjectStorage).accessCache(0xc009cfa090, 0xc017d4c0c1, 0x31, 0x3f, 0xc00019b401, 0x0, 0x0)
	/github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200402214644-8da1ccad4605/objectstorage/object_storage.go:432 +0x164
github.com/iotaledger/hive.go/objectstorage.(*ObjectStorage).Load(0xc009cfa090, 0xc017d4c0c1, 0x31, 0x3f, 0x2008180, 0xc05ffa4aa0)
	/github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200402214644-8da1ccad4605/objectstorage/object_storage.go:112 +0x6c
github.com/gohornet/hornet/pkg/model/tangle.ForEachTransaction.func1(0xc017d4c0c1, 0x31, 0x3f, 0x2000ba0, 0xc05ffa3100, 0xc05ffa3100)
	/__w/hornet/hornet/pkg/model/tangle/transaction_storage.go:208 +0xf4
github.com/iotaledger/hive.go/objectstorage.(*ObjectStorage).ForEach.func3(0xc013356150, 0xc000190000, 0xc013356150)
	/github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200402214644-8da1ccad4605/objectstorage/object_storage.go:376 +0x357
github.com/dgraph-io/badger/v2.(*DB).View(0xc000156d80, 0xc00019b728, 0x0, 0x0)
	/github/home/go/pkg/mod/github.com/mu!xxer/badger/v2@v2.0.3-hotfix/txn.go:716 +0x92
github.com/iotaledger/hive.go/objectstorage.(*ObjectStorage).ForEach(0xc009cfa000, 0xc00019b798, 0x0, 0x0, 0x0)
	/github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200402214644-8da1ccad4605/objectstorage/object_storage.go:332 +0x120
github.com/gohornet/hornet/pkg/model/tangle.ForEachTransaction(0xc00019b898)
	/__w/hornet/hornet/pkg/model/tangle/transaction_storage.go:205 +0x63
github.com/gohornet/hornet/plugins/tangle.cleanupTransactions(0xc015311080)
	/__w/hornet/hornet/plugins/tangle/revalidation.go:153 +0x11f
github.com/gohornet/hornet/plugins/tangle.revalidateDatabase(0xc000135860, 0x1)
	/__w/hornet/hornet/plugins/tangle/revalidation.go:80 +0x102
github.com/gohornet/hornet/plugins/tangle.run(0xc0001549c0)
	/__w/hornet/hornet/plugins/tangle/plugin.go:91 +0x16b
github.com/iotaledger/hive.go/node.pluginCaller(0xf67320, 0x1e739e0, 0xc0003beb00, 0x1, 0x1)
	/github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200402214644-8da1ccad4605/node/events.go:14 +0x62
github.com/iotaledger/hive.go/events.(*Event).Trigger(0xc0001a7ce0, 0xc0003beb00, 0x1, 0x1)
	/github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200402214644-8da1ccad4605/events/event.go:31 +0xdb
github.com/iotaledger/hive.go/node.(*Node).Run(0xc00001f8c0)
	/github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200402214644-8da1ccad4605/node/node.go:116 +0xe9
github.com/iotaledger/hive.go/node.Run(0xc0000a5f00, 0x1, 0x1, 0xc0004a6580)
	/github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200402214644-8da1ccad4605/node/node.go:52 +0x52
main.main()
	/__w/hornet/hornet/main.go:61 +0x168

goroutine 19 [chan receive, 3 minutes]:
github.com/iotaledger/hive.go/objectstorage.init.0.func1()
	/github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200402214644-8da1ccad4605/objectstorage/leak_detection.go:146 +0x43
created by github.com/iotaledger/hive.go/objectstorage.init.0
	/github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200402214644-8da1ccad4605/objectstorage/leak_detection.go:144 +0x35

goroutine 20 [select, 3 minutes]:
github.com/iotaledger/hive.go/batchworkerpool.(*BatchWorkerPool).startBatchDispatcher.func1(0xc000136a80)
	/github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200402214644-8da1ccad4605/batchworkerpool/batchworkerpool.go:142 +0xfb
created by github.com/iotaledger/hive.go/batchworkerpool.(*BatchWorkerPool).startBatchDispatcher
	/github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200402214644-8da1ccad4605/batchworkerpool/batchworkerpool.go:140 +0x5c

goroutine 21 [select, 3 minutes]:
github.com/iotaledger/hive.go/batchworkerpool.(*BatchWorkerPool).startBatchWorkers.func1(0xc000136a80)
	/github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200402214644-8da1ccad4605/batchworkerpool/batchworkerpool.go:180 +0xd3
created by github.com/iotaledger/hive.go/batchworkerpool.(*BatchWorkerPool).startBatchWorkers
	/github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200402214644-8da1ccad4605/batchworkerpool/batchworkerpool.go:176 +0x5e

goroutine 22 [select, 3 minutes]:
github.com/iotaledger/hive.go/batchworkerpool.(*BatchWorkerPool).startBatchWorkers.func1(0xc000136a80)
	/github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200402214644-8da1ccad4605/batchworkerpool/batchworkerpool.go:180 +0xd3
created by github.com/iotaledger/hive.go/batchworkerpool.(*BatchWorkerPool).startBatchWorkers
	/github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200402214644-8da1ccad4605/batchworkerpool/batchworkerpool.go:176 +0x5e

goroutine 23 [select, 3 minutes]:
github.com/iotaledger/hive.go/batchworkerpool.(*BatchWorkerPool).startBatchWorkers.func1(0xc000136a80)
	/github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200402214644-8da1ccad4605/batchworkerpool/batchworkerpool.go:180 +0xd3
created by github.com/iotaledger/hive.go/batchworkerpool.(*BatchWorkerPool).startBatchWorkers
	/github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200402214644-8da1ccad4605/batchworkerpool/batchworkerpool.go:176 +0x5e

goroutine 24 [select, 3 minutes]:
github.com/iotaledger/hive.go/batchworkerpool.(*BatchWorkerPool).startBatchWorkers.func1(0xc000136a80)
	/github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200402214644-8da1ccad4605/batchworkerpool/batchworkerpool.go:180 +0xd3
created by github.com/iotaledger/hive.go/batchworkerpool.(*BatchWorkerPool).startBatchWorkers
	/github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200402214644-8da1ccad4605/batchworkerpool/batchworkerpool.go:176 +0x5e

goroutine 25 [select, 3 minutes]:
github.com/iotaledger/hive.go/batchworkerpool.(*BatchWorkerPool).startBatchWorkers.func1(0xc000136a80)
	/github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200402214644-8da1ccad4605/batchworkerpool/batchworkerpool.go:180 +0xd3
created by github.com/iotaledger/hive.go/batchworkerpool.(*BatchWorkerPool).startBatchWorkers
	/github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200402214644-8da1ccad4605/batchworkerpool/batchworkerpool.go:176 +0x5e

goroutine 26 [select, 3 minutes]:
github.com/iotaledger/hive.go/batchworkerpool.(*BatchWorkerPool).startBatchWorkers.func1(0xc000136a80)
	/github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200402214644-8da1ccad4605/batchworkerpool/batchworkerpool.go:180 +0xd3
created by github.com/iotaledger/hive.go/batchworkerpool.(*BatchWorkerPool).startBatchWorkers
	/github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200402214644-8da1ccad4605/batchworkerpool/batchworkerpool.go:176 +0x5e

goroutine 27 [select, 3 minutes]:
github.com/iotaledger/hive.go/batchworkerpool.(*BatchWorkerPool).startBatchWorkers.func1(0xc000136a80)
	/github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200402214644-8da1ccad4605/batchworkerpool/batchworkerpool.go:180 +0xd3
created by github.com/iotaledger/hive.go/batchworkerpool.(*BatchWorkerPool).startBatchWorkers
	/github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200402214644-8da1ccad4605/batchworkerpool/batchworkerpool.go:176 +0x5e

goroutine 28 [select, 3 minutes]:
github.com/iotaledger/hive.go/batchworkerpool.(*BatchWorkerPool).startBatchWorkers.func1(0xc000136a80)
	/github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200402214644-8da1ccad4605/batchworkerpool/batchworkerpool.go:180 +0xd3
created by github.com/iotaledger/hive.go/batchworkerpool.(*BatchWorkerPool).startBatchWorkers
	/github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200402214644-8da1ccad4605/batchworkerpool/batchworkerpool.go:176 +0x5e

goroutine 30 [select, 3 minutes]:
github.com/patrickmn/go-cache.(*janitor).Run(0xc000427080, 0xc000455580)
	/github/home/go/pkg/mod/github.com/patrickmn/go-cache@v2.1.0+incompatible/cache.go:1079 +0xd5
created by github.com/patrickmn/go-cache.runJanitor
	/github/home/go/pkg/mod/github.com/patrickmn/go-cache@v2.1.0+incompatible/cache.go:1099 +0xa9

goroutine 8 [select]:
github.com/dgraph-io/ristretto.(*defaultPolicy).processItems(0xc0001ca3f0)
	/github/home/go/pkg/mod/github.com/dgraph-io/ristretto@v0.0.2-0.20200115201040-8f368f2f2ab3/policy.go:96 +0xbe
created by github.com/dgraph-io/ristretto.newDefaultPolicy
	/github/home/go/pkg/mod/github.com/dgraph-io/ristretto@v0.0.2-0.20200115201040-8f368f2f2ab3/policy.go:80 +0x129

goroutine 36 [syscall, 3 minutes]:
os/signal.signal_recv(0x1e75818)
	/usr/local/go/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.Notify.func1
	/usr/local/go/src/os/signal/signal.go:127 +0x44

goroutine 53 [chan receive, 3 minutes]:
github.com/gohornet/hornet/plugins/gracefulshutdown.configure.func1(0xc0000177a0)
	/__w/hornet/hornet/plugins/gracefulshutdown/plugin.go:32 +0x38
created by github.com/gohornet/hornet/plugins/gracefulshutdown.configure
	/__w/hornet/hornet/plugins/gracefulshutdown/plugin.go:31 +0x129

goroutine 54 [select]:
github.com/dgraph-io/badger/v2/y.(*WaterMark).process(0xc0004a95c0, 0xc0003a6d00)
	/github/home/go/pkg/mod/github.com/mu!xxer/badger/v2@v2.0.3-hotfix/y/watermark.go:229 +0x2d7
created by github.com/dgraph-io/badger/v2/y.(*WaterMark).Init
	/github/home/go/pkg/mod/github.com/mu!xxer/badger/v2@v2.0.3-hotfix/y/watermark.go:78 +0xa6

goroutine 55 [select, 2 minutes]:
github.com/dgraph-io/badger/v2/y.(*WaterMark).process(0xc0004a9600, 0xc0003a6d00)
	/github/home/go/pkg/mod/github.com/mu!xxer/badger/v2@v2.0.3-hotfix/y/watermark.go:229 +0x2d7
created by github.com/dgraph-io/badger/v2/y.(*WaterMark).Init
	/github/home/go/pkg/mod/github.com/mu!xxer/badger/v2@v2.0.3-hotfix/y/watermark.go:78 +0xa6

goroutine 56 [select]:
github.com/dgraph-io/ristretto.(*Cache).processItems(0xc00041a1e0)
	/github/home/go/pkg/mod/github.com/dgraph-io/ristretto@v0.0.2-0.20200115201040-8f368f2f2ab3/cache.go:269 +0xbc
created by github.com/dgraph-io/ristretto.NewCache
	/github/home/go/pkg/mod/github.com/dgraph-io/ristretto@v0.0.2-0.20200115201040-8f368f2f2ab3/cache.go:155 +0x1f3

goroutine 57 [select]:
github.com/dgraph-io/badger/v2.(*DB).updateSize(0xc000156d80, 0xc000406380)
	/github/home/go/pkg/mod/github.com/mu!xxer/badger/v2@v2.0.3-hotfix/db.go:1123 +0x149
created by github.com/dgraph-io/badger/v2.Open
	/github/home/go/pkg/mod/github.com/mu!xxer/badger/v2@v2.0.3-hotfix/db.go:344 +0x9b3

goroutine 250 [select]:
github.com/dgraph-io/badger/v2.(*levelsController).runWorker(0xc00021a300, 0xc000406f60)
	/github/home/go/pkg/mod/github.com/mu!xxer/badger/v2@v2.0.3-hotfix/levels.go:361 +0x20c
created by github.com/dgraph-io/badger/v2.(*levelsController).startCompact
	/github/home/go/pkg/mod/github.com/mu!xxer/badger/v2@v2.0.3-hotfix/levels.go:342 +0x88

goroutine 251 [chan receive, 2 minutes]:
github.com/dgraph-io/badger/v2.(*DB).flushMemtable(0xc000156d80, 0xc000406f80, 0x0, 0x0)
	/github/home/go/pkg/mod/github.com/mu!xxer/badger/v2@v2.0.3-hotfix/db.go:1030 +0xb7
github.com/dgraph-io/badger/v2.Open.func4(0xc000010038)
	/github/home/go/pkg/mod/github.com/mu!xxer/badger/v2@v2.0.3-hotfix/db.go:361 +0x37
created by github.com/dgraph-io/badger/v2.Open
	/github/home/go/pkg/mod/github.com/mu!xxer/badger/v2@v2.0.3-hotfix/db.go:360 +0x1474

goroutine 254 [select, 2 minutes]:
github.com/dgraph-io/badger/v2.(*DB).doWrites(0xc000156d80, 0xc000407300)
	/github/home/go/pkg/mod/github.com/mu!xxer/badger/v2@v2.0.3-hotfix/db.go:802 +0x3fa
created by github.com/dgraph-io/badger/v2.Open
	/github/home/go/pkg/mod/github.com/mu!xxer/badger/v2@v2.0.3-hotfix/db.go:395 +0xf59

goroutine 253 [select, 2 minutes]:
github.com/dgraph-io/badger/v2.(*valueLog).flushDiscardStats(0xc000156f60)
	/github/home/go/pkg/mod/github.com/mu!xxer/badger/v2@v2.0.3-hotfix/value.go:1864 +0x175
created by github.com/dgraph-io/badger/v2.(*valueLog).open
	/github/home/go/pkg/mod/github.com/mu!xxer/badger/v2@v2.0.3-hotfix/value.go:1094 +0x6c

goroutine 255 [chan receive, 3 minutes]:
github.com/dgraph-io/badger/v2.(*valueLog).waitOnGC(0xc000156f60, 0xc000407320)
	/github/home/go/pkg/mod/github.com/mu!xxer/badger/v2@v2.0.3-hotfix/value.go:1767 +0x63
created by github.com/dgraph-io/badger/v2.Open
	/github/home/go/pkg/mod/github.com/mu!xxer/badger/v2@v2.0.3-hotfix/db.go:399 +0x1181

goroutine 256 [select, 3 minutes]:
github.com/dgraph-io/badger/v2.(*publisher).listenForUpdates(0xc000347020, 0xc000407340)
	/github/home/go/pkg/mod/github.com/mu!xxer/badger/v2@v2.0.3-hotfix/publisher.go:67 +0x161
created by github.com/dgraph-io/badger/v2.Open
	/github/home/go/pkg/mod/github.com/mu!xxer/badger/v2@v2.0.3-hotfix/db.go:403 +0x1038

goroutine 823 [select]:
github.com/iotaledger/hive.go/objectstorage.(*BatchedWriter).runBatchWriter(0xc0138b26f0)
	/github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200402214644-8da1ccad4605/objectstorage/batch_writer.go:134 +0x15a
created by github.com/iotaledger/hive.go/objectstorage.(*BatchedWriter).StartBatchWriter
	/github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200402214644-8da1ccad4605/objectstorage/batch_writer.go:43 +0x93

goroutine 7231 [select]:
github.com/iotaledger/hive.go/objectstorage.(*BatchedWriter).runBatchWriter(0xc000402ea0)
	/github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200402214644-8da1ccad4605/objectstorage/batch_writer.go:134 +0x15a
created by github.com/iotaledger/hive.go/objectstorage.(*BatchedWriter).StartBatchWriter
	/github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200402214644-8da1ccad4605/objectstorage/batch_writer.go:43 +0x93

goroutine 548 [semacquire, 3 minutes]:
sync.runtime_Semacquire(0xc015342b38)
	/usr/local/go/src/runtime/sema.go:56 +0x42
sync.(*WaitGroup).Wait(0xc015342b30)
	/usr/local/go/src/sync/waitgroup.go:130 +0x64
github.com/spf13/viper.(*Viper).WatchConfig.func1(0xc000148b40, 0xc015342ae0)
	/github/home/go/pkg/mod/github.com/spf13/viper@v1.6.2/viper.go:404 +0x338
created by github.com/spf13/viper.(*Viper).WatchConfig
	/github/home/go/pkg/mod/github.com/spf13/viper@v1.6.2/viper.go:343 +0x75

goroutine 7227 [select]:
github.com/iotaledger/hive.go/objectstorage.(*BatchedWriter).runBatchWriter(0xc0138b2300)
	/github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200402214644-8da1ccad4605/objectstorage/batch_writer.go:134 +0x15a
created by github.com/iotaledger/hive.go/objectstorage.(*BatchedWriter).StartBatchWriter
	/github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200402214644-8da1ccad4605/objectstorage/batch_writer.go:43 +0x93

goroutine 277 [IO wait, 3 minutes]:
internal/poll.runtime_pollWait(0x7f9671f4be48, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc00cbca218, 0x72, 0x0, 0x0, 0x1142973)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc00cbca200, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:384 +0x1d4
net.(*netFD).accept(0xc00cbca200, 0xc013986da8, 0xc000101500, 0x7f969ba87e98)
	/usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc018900080, 0xc013986de8, 0x4185e8, 0x30)
	/usr/local/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc018900080, 0x1094a40, 0xc0187366f0, 0xfaf960, 0x2747200)
	/usr/local/go/src/net/tcpsock.go:261 +0x64
net/http.(*Server).Serve(0xc0002940e0, 0x1ff6720, 0xc018900080, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2901 +0x25d
net/http.(*Server).ListenAndServe(0xc0002940e0, 0xc0002940e0, 0x449236)
	/usr/local/go/src/net/http/server.go:2830 +0xb7
net/http.ListenAndServe(0x11494c2, 0xe, 0x0, 0x0, 0xc00020a5a0, 0xc0002302b8)
	/usr/local/go/src/net/http/server.go:3086 +0x74
created by github.com/gohornet/hornet/plugins/profiling.run
	/__w/hornet/hornet/plugins/profiling/plugin.go:25 +0x96

goroutine 552 [select]:
github.com/iotaledger/hive.go/objectstorage.(*BatchedWriter).runBatchWriter(0xc0138b25a0)
	/github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200402214644-8da1ccad4605/objectstorage/batch_writer.go:134 +0x15a
created by github.com/iotaledger/hive.go/objectstorage.(*BatchedWriter).StartBatchWriter
	/github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200402214644-8da1ccad4605/objectstorage/batch_writer.go:43 +0x93

goroutine 549 [runnable]:
syscall.Syscall6(0xe8, 0x112, 0xc015457b74, 0x7, 0xffffffffffffffff, 0x0, 0x0, 0x1, 0x7, 0x0)
	/usr/local/go/src/syscall/asm_linux_amd64.s:41 +0x5
golang.org/x/sys/unix.EpollWait(0x112, 0xc015457b74, 0x7, 0x7, 0xffffffffffffffff, 0x0, 0xc015457c4c, 0xc015457b90)
	/github/home/go/pkg/mod/golang.org/x/sys@v0.0.0-20200323222414-85ca7c5b95cd/unix/zsyscall_linux_amd64.go:76 +0x72
github.com/fsnotify/fsnotify.(*fdPoller).wait(0xc0000a7d40, 0xc015457c00, 0x2, 0x0)
	/github/home/go/pkg/mod/github.com/fsnotify/fsnotify@v1.4.9/inotify_poller.go:86 +0x91
github.com/fsnotify/fsnotify.(*Watcher).readEvents(0xc000140f50)
	/github/home/go/pkg/mod/github.com/fsnotify/fsnotify@v1.4.9/inotify.go:192 +0x1f8
created by github.com/fsnotify/fsnotify.NewWatcher
	/github/home/go/pkg/mod/github.com/fsnotify/fsnotify@v1.4.9/inotify.go:59 +0x1a5

goroutine 550 [runnable]:
github.com/spf13/viper.(*Viper).WatchConfig.func1.1(0xc000140f50, 0xc015342b30, 0xc000232380, 0x3e, 0xc000232380, 0x3e, 0xc0138fff40, 0xc000148b40)
	/github/home/go/pkg/mod/github.com/spf13/viper@v1.6.2/viper.go:365 +0xe6
created by github.com/spf13/viper.(*Viper).WatchConfig.func1
	/github/home/go/pkg/mod/github.com/spf13/viper@v1.6.2/viper.go:363 +0x2e7

goroutine 551 [select]:
github.com/iotaledger/hive.go/objectstorage.(*BatchedWriter).runBatchWriter(0xc0138b2450)
	/github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200402214644-8da1ccad4605/objectstorage/batch_writer.go:134 +0x15a
created by github.com/iotaledger/hive.go/objectstorage.(*BatchedWriter).StartBatchWriter
	/github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200402214644-8da1ccad4605/objectstorage/batch_writer.go:43 +0x93

goroutine 553 [select]:
github.com/iotaledger/hive.go/objectstorage.(*BatchedWriter).runBatchWriter(0xc0138b2840)
	/github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200402214644-8da1ccad4605/objectstorage/batch_writer.go:134 +0x15a
created by github.com/iotaledger/hive.go/objectstorage.(*BatchedWriter).StartBatchWriter
	/github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200402214644-8da1ccad4605/objectstorage/batch_writer.go:43 +0x93

goroutine 845 [select]:
github.com/iotaledger/hive.go/objectstorage.(*BatchedWriter).runBatchWriter(0xc0138b2060)
	/github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200402214644-8da1ccad4605/objectstorage/batch_writer.go:134 +0x15a
created by github.com/iotaledger/hive.go/objectstorage.(*BatchedWriter).StartBatchWriter
	/github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200402214644-8da1ccad4605/objectstorage/batch_writer.go:43 +0x93
```

**Comment by muXxer** [comment]
Should be fixed in latest develop
