### ISSUE TITLE
Hornet crash & corrupt DB after telnet to PMQ 

### ISSUE THREAD

**Issue by raspstar** [iotaledger/hornet#403]
Hi,

randomly, when somebody tries to connect to PMQ via a non-conform client like eg. telnet, Hornet 0.3.10 crashes and leaves a corrupted DB.

Is this a known problem?

regards,

Raspstar
```
*** after Crash ***

● hornet.service - Hornet IOTA
   Loaded: loaded (/etc/systemd/system/hornet.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2020-04-27 12:31:30 UTC; 13s ago
  Process: 27073 ExecStop=/usr/bin/docker stop --time 1200 hornet (code=exited, status=0/SUCCESS)
  Process: 27171 ExecStart=/usr/bin/docker run --name hornet --net=host --user=39999 --cap-drop=ALL -v /etc/localtime:/etc/localtime:ro,Z -v /var/lib/hornet/mainnetdb:/app/mainnetdb:rw,Z -v /var/lib/hornet/config.json:/app/config.json:ro,Z -v /var/lib/hornet/neighbors.json:/app/neighbors.json:rw,Z -v /var/lib/hornet/mqtt_config.json:/app/mqtt_config.json:ro,Z -v /var/lib/hornet/snapshot:/app/snapshot:rw,Z -v /var/lib/hornet/tanglemonitor/frontend:/app/tanglemonitor/frontend:ro,Z -v /var/lib/hornet/tanglevisualiser/webroot:/app/IOTAtangle/webroot:ro,Z -v /var/lib/hornet/socket.io-client/dist/socket.io.js:/app/socket.io-client/dist/socket.io.js:ro,Z --ulimit nofile=65535:65535 $DOCKER_OPTS ${HORNET_IMAGE}:${TAG} $OPTIONS (code=exited, status=2)
  Process: 27135 ExecStartPre=/bin/bash -c /usr/bin/docker rm hornet || /bin/true (code=exited, status=0/SUCCESS)
 Main PID: 27171 (code=exited, status=2)

Apr 27 12:31:28 node docker[27171]: reqQ: 00000, reqQMs: 0, processor: 00000, LSMI/LMI: 1392733/1392733, addrsMarked: 164, bndlsValidated: 1085, txReqs(Tx/Rx): 0/0, newTxs: 1226, TPS: 94 (in) / 7 (new) / 12 (out)
Apr 27 12:31:29 node docker[27171]: reqQ: 00000, reqQMs: 0, processor: 00000, LSMI/LMI: 1392733/1392733, addrsMarked: 164, bndlsValidated: 1097, txReqs(Tx/Rx): 0/0, newTxs: 1238, TPS: 32 (in) / 3 (new) / 5 (out)
Apr 27 12:31:30 node docker[27171]: panic: zmq4: could not exchange greetings: zmq4: could not recv greeting: unexpected EOF
Apr 27 12:31:30 node docker[27171]: goroutine 355 [running]:
Apr 27 12:31:30 node docker[27171]: github.com/go-zeromq/zmq4.(*socket).accept(0xc004c6a160)
Apr 27 12:31:30 node docker[27171]:         /go/pkg/mod/github.com/go-zeromq/zmq4@v0.7.0/socket.go:196 +0x23d
Apr 27 12:31:30 node docker[27171]: created by github.com/go-zeromq/zmq4.(*socket).Listen
Apr 27 12:31:30 node docker[27171]:         /go/pkg/mod/github.com/go-zeromq/zmq4@v0.7.0/socket.go:174 +0x14c
Apr 27 12:31:30 node systemd[1]: hornet.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 27 12:31:30 node systemd[1]: hornet.service: Failed with result 'exit-code'.
(END)

*** after attempted Restart ***

● hornet.service - Hornet IOTA
   Loaded: loaded (/etc/systemd/system/hornet.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2020-04-27 12:33:00 UTC; 12s ago
  Process: 27073 ExecStop=/usr/bin/docker stop --time 1200 hornet (code=exited, status=0/SUCCESS)
  Process: 28458 ExecStart=/usr/bin/docker run --name hornet --net=host --user=39999 --cap-drop=ALL -v /etc/localtime:/etc/localtime:ro,Z -v /var/lib/hornet/mainnetdb:/app/mainnetdb:rw,Z -v /var/lib/hornet/config.json:/app/config.json:ro,Z -v /var/lib/hornet/neighbors.json:/app/neighbors.json:rw,Z -v /var/lib/hornet/mqtt_config.json:/app/mqtt_config.json:ro,Z -v /var/lib/hornet/snapshot:/app/snapshot:rw,Z -v /var/lib/hornet/tanglemonitor/frontend:/app/tanglemonitor/frontend:ro,Z -v /var/lib/hornet/tanglevisualiser/webroot:/app/IOTAtangle/webroot:ro,Z -v /var/lib/hornet/socket.io-client/dist/socket.io.js:/app/socket.io-client/dist/socket.io.js:ro,Z --ulimit nofile=65535:65535 $DOCKER_OPTS ${HORNET_IMAGE}:${TAG} $OPTIONS (code=exited, status=2)
  Process: 28434 ExecStartPre=/bin/bash -c /usr/bin/docker rm hornet || /bin/true (code=exited, status=0/SUCCESS)
 Main PID: 28458 (code=exited, status=2)

Apr 27 12:33:00 node docker[28458]: github.com/iotaledger/hive.go/node.(*Node).configure(0xc0000332c0, 0xc00049a000, 0xe, 0xe)
Apr 27 12:33:00 node docker[28458]:         /go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200107205115-986a54f82a30/node/node.go:77 +0x102
Apr 27 12:33:00 node docker[28458]: github.com/iotaledger/hive.go/node.New(0xc0004ddf48, 0x1, 0x1, 0xf3c3c0)
Apr 27 12:33:00 node docker[28458]:         /go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200107205115-986a54f82a30/node/node.go:33 +0x124
Apr 27 12:33:00 node docker[28458]: github.com/iotaledger/hive.go/node.Run(0xc0004ddf48, 0x1, 0x1, 0xc00000e2e0)
Apr 27 12:33:00 node docker[28458]:         /go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200107205115-986a54f82a30/node/node.go:46 +0x3f
Apr 27 12:33:00 node docker[28458]: main.main()
Apr 27 12:33:00 node docker[28458]:         /__w/hornet/hornet/main.go:35 +0x22b
Apr 27 12:33:00 node systemd[1]: hornet.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 27 12:33:00 node systemd[1]: hornet.service: Failed with result 'exit-code'.

```

**Comment by IoTMOD** [comment]
Hi @raspstar,

thank you for your issue report.
This is a known bug in HORNET 0.3.0 (https://github.com/gohornet/hornet/issues/7)

It'll be fixed with the HORNET 0.4.0 release. 
You can already test our HORNET 0.4.0 release candidates if you need ZMQ (https://github.com/gohornet/hornet/releases/tag/v0.4.0-rc8).
Otherwise please disable the ZMQ plugin to fix this issue in HORNET 0.3.0
