### ISSUE TITLE
invalid page allocation:0

### ISSUE THREAD

**Issue by knight-ryu12** [iotaledger/hornet#469]
**Describe the bug**
It fails to boot upon making DB.

**To Reproduce**
Booting hornet does.

**Environment information:**
 - OS: Arch Linux
 - RAM: 4GB
 - Cores: 4 Cores
 - HORNET version rc12

**Additional context**
````
2020-05-30T17:27:43+09:00       INFO    Snapshot        importing solid entry points
2020-05-30T17:27:43+09:00       INFO    Snapshot        importing seen milestones
2020-05-30T17:27:43+09:00       INFO    Snapshot        importing ledger state
panic: invalid page allocation: 0

goroutine 1 [running]:
go.etcd.io/bbolt.(*freelist).arrayAllocate(0xc000102100, 0xf, 0x1, 0x0)
        /github/home/go/pkg/mod/go.etcd.io/bbolt@v1.3.4/freelist.go:134 +0x2cd
go.etcd.io/bbolt.(*DB).allocate(0xc000352000, 0xf, 0x1, 0x0, 0xc000402280, 0xc0003de070)
        /github/home/go/pkg/mod/go.etcd.io/bbolt@v1.3.4/db.go:931 +0xa5
go.etcd.io/bbolt.(*Tx).allocate(0xc0003ac0e0, 0x1, 0x7f439f00b000, 0x292f380, 0x0)
        /github/home/go/pkg/mod/go.etcd.io/bbolt@v1.3.4/tx.go:499 +0x4a
go.etcd.io/bbolt.(*node).spill(0xc0003de070, 0xc006f1f6c8, 0x1)
        /github/home/go/pkg/mod/go.etcd.io/bbolt@v1.3.4/node.go:369 +0x26e
go.etcd.io/bbolt.(*Bucket).spill(0xc0003ac0f8, 0x36b9cb1945, 0x29010c0)
        /github/home/go/pkg/mod/go.etcd.io/bbolt@v1.3.4/bucket.go:570 +0x473
go.etcd.io/bbolt.(*Tx).Commit(0xc0003ac0e0, 0x0, 0x0)
        /github/home/go/pkg/mod/go.etcd.io/bbolt@v1.3.4/tx.go:161 +0xec
go.etcd.io/bbolt.(*DB).Update(0xc000352000, 0xc006f1f9b8, 0x0, 0x0)
        /github/home/go/pkg/mod/go.etcd.io/bbolt@v1.3.4/db.go:701 +0xf6
github.com/iotaledger/hive.go/kvstore/bolt.(*boltStore).Set(0xc0003e8020, 0xc008a594c0, 0xb, 0xb, 0x292d628, 0x0, 0x0, 0x0, 0x0)
        /github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200520215850-06bf0dc5c0ef/kvstore/bolt/bolt.go:117 +0xaf
github.com/gohornet/hornet/pkg/model/tangle.MarkDatabaseCorrupted()
        /__w/hornet/hornet/pkg/model/tangle/health_db.go:24 +0x94
github.com/gohornet/hornet/plugins/snapshot.configure(0xc0000d7680)
        /__w/hornet/hornet/plugins/snapshot/plugin.go:143 +0x618
github.com/iotaledger/hive.go/node.pluginCaller(0xfd5000, 0x1f33a58, 0xc00049e560, 0x1, 0x1)
        /github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200520215850-06bf0dc5c0ef/node/events.go:14 +0x62
github.com/iotaledger/hive.go/events.(*Event).Trigger(0xc00031c9f0, 0xc00049e560, 0x1, 0x1)
        /github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200520215850-06bf0dc5c0ef/events/event.go:31 +0xdb
github.com/iotaledger/hive.go/node.(*Node).configure(0xc0002967b0, 0xc000516a50, 0x15, 0x16)
        /github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200520215850-06bf0dc5c0ef/node/node.go:93 +0xf6
github.com/iotaledger/hive.go/node.New(0xc0004bfe98, 0x1, 0x1, 0x1083d60)
        /github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200520215850-06bf0dc5c0ef/node/node.go:38 +0x153
github.com/iotaledger/hive.go/node.Run(0xc0004bfe98, 0x1, 0x1, 0xc000294220)
        /github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200520215850-06bf0dc5c0ef/node/node.go:51 +0x3f
main.main()
        /__w/hornet/hornet/main.go:66 +0x23f
```

**Comment by Mke91** [comment]
This error i found without really investigating if freelist.go is used
https://github.com/boltdb/bolt/blob/master/freelist.go

// allocate returns the starting page id of a contiguous list of pages of a given size.
// If a contiguous block cannot be found then 0 is returned.
func (f *freelist) allocate(n int) pgid {
	if len(f.ids) == 0 {
		return 0
	}

	var initial, previd pgid
	for i, id := range f.ids {
		if id <= 1 {
			panic(fmt.Sprintf("invalid page allocation: %d", id))
		}

		// Reset initial page if this is not contiguous.
		if previd == 0 || id-previd != 1 {
			initial = id
		}

**Comment by muXxer** [comment]
@knight-ryu12 were you out of disk space?

**Comment by knight-ryu12** [comment]
Sad to say but today my server machine died of bad HDD.

I can't do anymore confirmation about this matters until I get new HDD/SSD.
