### ISSUE TITLE
snapshot downloadURL questions

### ISSUE THREAD

**Issue by ghost** [iotaledger/hornet#475]
**Describe the bug**

**To Reproduce**
- Download and unpack hornet
- download snapshot https://dbfiles.iota.org/mainnet/hornet/latest-export.bin
- I only edited the 'db' part in config.json to add an existing folder
- start Hornet with `cd conf && ./hornet`
- Got the following error message:
```
2020/06/03 08:42:20 error: Config File "peering" Not Found in "[/conf]"
2020-06-03T08:42:20Z    INFO    Node    Loading Plugin: Peering ... done
2020-06-03T08:42:20Z    INFO    Node    Loading Plugin: WarpSync ... done
2020-06-03T08:42:20Z    INFO    Node    Loading Plugin: Tip-Sel ... done
2020-06-03T08:42:20Z    INFO    Node    Loading Plugin: Metrics ... done
2020-06-03T08:42:20Z    PANIC   Snapshot        no download URL given for local snapshot under config option 'snapshots.local.downloadURL
github.com/gohornet/hornet/plugins/snapshot.configure
        /__w/hornet/hornet/plugins/snapshot/plugin.go:147
github.com/iotaledger/hive.go/node.pluginCaller
        /github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200520215850-06bf0dc5c0ef/node/events.go:14
github.com/iotaledger/hive.go/events.(*Event).Trigger
        /github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200520215850-06bf0dc5c0ef/events/event.go:31
github.com/iotaledger/hive.go/node.(*Node).configure
        /github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200520215850-06bf0dc5c0ef/node/node.go:93
github.com/iotaledger/hive.go/node.New
        /github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200520215850-06bf0dc5c0ef/node/node.go:38
github.com/iotaledger/hive.go/node.Run
        /github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200520215850-06bf0dc5c0ef/node/node.go:51
main.main
        /__w/hornet/hornet/main.go:66
runtime.main
        /usr/local/go/src/runtime/proc.go:203
panic: no download URL given for local snapshot under config option 'snapshots.local.downloadURL

goroutine 1 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0001528f0, 0x0, 0x0, 0x0)
        /github/home/go/pkg/mod/go.uber.org/zap@v1.13.0/zapcore/entry.go:230 +0x545
go.uber.org/zap.(*SugaredLogger).log(0xc000010390, 0x4, 0x0, 0x0, 0xc0004a7ba8, 0x1, 0x1, 0x0, 0x0, 0x0)
        /github/home/go/pkg/mod/go.uber.org/zap@v1.13.0/sugar.go:234 +0x100
go.uber.org/zap.(*SugaredLogger).Panic(...)
        /github/home/go/pkg/mod/go.uber.org/zap@v1.13.0/sugar.go:123
github.com/gohornet/hornet/plugins/snapshot.configure(0xc00007c440)
        /__w/hornet/hornet/plugins/snapshot/plugin.go:147 +0x6f4
github.com/iotaledger/hive.go/node.pluginCaller(0xfd8220, 0x1f37118, 0xc000032ca0, 0x1, 0x1)
        /github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200520215850-06bf0dc5c0ef/node/events.go:14 +0x62
github.com/iotaledger/hive.go/events.(*Event).Trigger(0xc00019e360, 0xc000032ca0, 0x1, 0x1)
        /github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200520215850-06bf0dc5c0ef/events/event.go:31 +0xdb
github.com/iotaledger/hive.go/node.(*Node).configure(0xc0003224e0, 0xc0002e62c0, 0x15, 0x16)
        /github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200520215850-06bf0dc5c0ef/node/node.go:93 +0xf6
github.com/iotaledger/hive.go/node.New(0xc0005b9e98, 0x1, 0x1, 0x1087340)
        /github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200520215850-06bf0dc5c0ef/node/node.go:38 +0x153
github.com/iotaledger/hive.go/node.Run(0xc0005b9e98, 0x1, 0x1, 0xc0001ee900)
        /github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200520215850-06bf0dc5c0ef/node/node.go:51 +0x3f
main.main()
        /__w/hornet/hornet/main.go:66 +0x23f
```

**Expected behavior**
Hornet keeps running
**Environment information:**
 - OS: CentOS 8
 - RAM: N/A
 - Cores: N/A
 - HORNET version: 0.4.0-rc13-3

**Additional context**
It is not clear to me what has to be changed in the config.

**Comment by muXxer** [comment]
Hi, first you don't have to download the snapshot yourself. Hornet does that for you automatically at startup, if no DB or snapshot exists.

Your problem is, that a needed config file can't be found.
`error: Config File "peering" Not Found in "[/conf]"`
There should be a `peering.json` somewhere.

Are you using really old config files?
Use the ones that are in the package.

**Comment by ghost** [comment]
Thanks a lot, yes, I was using the config from 'master' :)
