### ISSUE TITLE
Panic: send on closed channel

### ISSUE THREAD

**Issue by uwec** [iotaledger/hornet#609]
**Describe the bug**
Node was running fine since 3h, when issue poped up.

**Environment information:**
 - OS: Windows 10
 - RAM: 4 GB
 - Cores: [e.g. 12 Cores]
 - Type: PC

 - HORNET version 0.5.0-RC10

**Additional context**
```
eq(qu/pe/proc/lat): 00000/00006/00000/0000ms, reqQMs: 0, processor: 00000, LSMI/LMI: 715787/715798, TPS (in/new/out): 00002/00001/00002, Tips (non-/semi-lazy): 135/0
2020-08-12T15:50:45+02:00       INFO    Tangle  Valid milestone detected! Index: 715800, Hash: XMEZUIYQWHXOBQTUWVYPEOWBMRJJOVCVDMP9SNTLGAZTNNFRKO9SJEQ9JIFTAKRQXJBZGJUHQPPCLZ999
2020-08-12T15:51:27+02:00       INFO    Dashboard       Removed websocket client
req(qu/pe/proc/lat): 00005/00001/00000/0000ms, reqQMs: 715792, processor: 00000, LSMI/LMI: 715787/715800, TPS (in/new/out): 00028/00014/00021, Tips (non-/semi-lazy): 135/0
2020-08-12T15:51:27+02:00       INFO    WarpSync        Synchronizing to milestone 715789
2020-08-12T15:51:27+02:00       INFO    Tangle  Valid milestone detected! Index: 715799, Hash: OQXFKXHBKQHXFCITGOHYSA9RPFAVFJLOOLMBLKOGSDVLLATBGURYEHGV9RLIS9EGSCQTYZJYDMGVPC999
2020-08-12T15:51:27+02:00       INFO    Tangle  Valid milestone detected! Index: 715801, Hash: SOVWORHAWHIDTGJPHXUVRJSPSRUSDLMNPIYPUPYZG9V9ZNBFJPBBMDHUSWWFGCSJIDOHH9VU9LMROZ999
2020-08-12T15:51:28+02:00       INFO    WarpSync        Manually starting solidifier, as some milestones are already in the database
2020-08-12T15:51:28+02:00       INFO    WarpSync        Checkpoint updated to milestone 715790
2020-08-12T15:51:28+02:00       INFO    Tangle  Run solidity check for Milestone (715788)...
2020-08-12T15:51:28+02:00       WARN    Tangle  Stopped solidifier due to missing tx -> Requested missing txs (1), collect: 0s
2020-08-12T15:51:28+02:00       INFO    Tangle  Milestone couldn't be solidified! 715788
2020-08-12T15:51:28+02:00       INFO    WarpSync        Target updated to milestone 715790
2020-08-12T15:51:28+02:00       INFO    WarpSync        Checkpoint updated to milestone 715791
2020-08-12T15:51:28+02:00       INFO    WarpSync        Target updated to milestone 715791
2020-08-12T15:51:28+02:00       INFO    WarpSync        Checkpoint updated to milestone 715792
2020-08-12T15:51:28+02:00       INFO    WarpSync        Target updated to milestone 715792
2020-08-12T15:51:28+02:00       INFO    WarpSync        Checkpoint updated to milestone 715793
2020-08-12T15:51:28+02:00       INFO    WarpSync        Target updated to milestone 715793
2020-08-12T15:51:28+02:00       INFO    WarpSync        Checkpoint updated to milestone 715794
2020-08-12T15:51:28+02:00       INFO    WarpSync        Target updated to milestone 715794
2020-08-12T15:51:28+02:00       INFO    WarpSync        Checkpoint updated to milestone 715795
2020-08-12T15:51:28+02:00       INFO    WarpSync        Target updated to milestone 715795
2020-08-12T15:51:28+02:00       INFO    WarpSync        Checkpoint updated to milestone 715796
2020-08-12T15:51:28+02:00       INFO    WarpSync        Target updated to milestone 715796
2020-08-12T15:51:28+02:00       INFO    WarpSync        Checkpoint updated to milestone 715797
2020-08-12T15:51:28+02:00       INFO    WarpSync        Target updated to milestone 715797
2020-08-12T15:51:28+02:00       INFO    WarpSync        Checkpoint updated to milestone 715798
2020-08-12T15:51:28+02:00       INFO    WarpSync        Target updated to milestone 715798
2020-08-12T15:51:28+02:00       INFO    WarpSync        Checkpoint updated to milestone 715799
2020-08-12T15:51:28+02:00       INFO    WarpSync        Target updated to milestone 715799
2020-08-12T15:51:28+02:00       INFO    WarpSync        Checkpoint updated to milestone 715800
2020-08-12T15:51:28+02:00       INFO    WarpSync        Target updated to milestone 715800
2020-08-12T15:51:28+02:00       INFO    WarpSync        Checkpoint updated to milestone 715801
2020-08-12T15:51:28+02:00       INFO    WarpSync        Target updated to milestone 715801
2020-08-12T15:51:28+02:00       INFO    WarpSync        Checkpoint updated to milestone 715802
2020-08-12T15:51:28+02:00       INFO    WarpSync        Target updated to milestone 715802
2020-08-12T15:51:28+02:00       INFO    WarpSync        Checkpoint updated to milestone 715803
2020-08-12T15:51:28+02:00       INFO    WarpSync        Target updated to milestone 715803
2020-08-12T15:51:28+02:00       INFO    WarpSync        Checkpoint updated to milestone 715804
2020-08-12T15:51:28+02:00       INFO    WarpSync        Target updated to milestone 715804
2020-08-12T15:51:28+02:00       INFO    Tangle  Valid milestone detected! Index: 715802, Hash: QLYFL9OCTZFSXUUGRSWRCUUGD9NXFAYYSAVPOJJXEBQ9SADDETINZVSWJLGHUXFBGZ9EFSJJIRPVVZ999
req(qu/pe/proc/lat): 00000/00007/00000/0000ms, reqQMs: 0, processor: 01107, LSMI/LMI: 715787/715802, TPS (in/new/out): 00028/00014/00021, Tips (non-/semi-lazy): 135/0
2020-08-12T15:51:28+02:00       INFO    Tangle  Valid milestone detected! Index: 715803, Hash: XXDUGFIKUAJSR9KTTWCAVHTNFWOKGL9DTONQYIURIBRK9XX9PNPAW9SJBY9ZKRVKTAVEOLJTD9NI9A999
2020-08-12T15:51:29+02:00       INFO    Tangle  Valid milestone detected! Index: 715804, Hash: IFDVQRKUUEKEZMEGHRCEPQ9NDDKPLPCSUM9CTAWLVAUAQYUGSDPSNASKFDNXVJERUJEKYRURDCQRFB999
2020-08-12T15:51:29+02:00       INFO    Tangle  Valid milestone detected! Index: 715805, Hash: QCQZNFIIVHOOPGH9ZSZRFTNJRNKOSORXU9YMPPIAWJGRCFPOC9YYUKY9GKHRSCRWQMNOHITKOBMSVD999
2020-08-12T15:51:29+02:00       INFO    WarpSync        Checkpoint updated to milestone 715805
2020-08-12T15:51:29+02:00       INFO    WarpSync        Target updated to milestone 715805
req(qu/pe/proc/lat): 00000/00003/00000/0000ms, reqQMs: 0, processor: 00000, LSMI/LMI: 715787/715805, TPS (in/new/out): 13534/02514/02366, Tips (non-/semi-lazy): 135/0
req(qu/pe/proc/lat): 00000/00000/00003/0000ms, reqQMs: 0, processor: 00602, LSMI/LMI: 715787/715805, TPS (in/new/out): 02645/00000/01629, Tips (non-/semi-lazy): 135/0
req(qu/pe/proc/lat): 00000/00000/00003/0000ms, reqQMs: 0, processor: 01286, LSMI/LMI: 715787/715805, TPS (in/new/out): 02645/00000/01629, Tips (non-/semi-lazy): 135/0
req(qu/pe/proc/lat): 00000/00002/00000/0000ms, reqQMs: 0, processor: 00000, LSMI/LMI: 715787/715805, TPS (in/new/out): 01694/01824/00771, Tips (non-/semi-lazy): 135/0
2020-08-12T15:51:33+02:00       INFO    Dashboard       WebSocket client connection established
req(qu/pe/proc/lat): 00000/00002/00000/0000ms, reqQMs: 0, processor: 00000, LSMI/LMI: 715787/715805, TPS (in/new/out): 00584/00200/00514, Tips (non-/semi-lazy): 135/0
2020-08-12T15:52:58+02:00       INFO    Peering dropping autopeered neighbor 95.217.18.238:14626 / X4wd3my8o6t because 76.14% of the messages in the last minute were dropped
2020-08-12T15:52:58+02:00       INFO    Peering dropping autopeered neighbor 31.16.36.233:14626 / Ctc1qska5hZ because 76.15% of the messages in the last minute were dropped
2020-08-12T15:52:58+02:00       INFO    Dashboard       Removed websocket client
2020-08-12T15:52:58+02:00       INFO    Peering disconnected 95.217.18.238:15600
2020-08-12T15:52:58+02:00       INFO    Autopeering     removing: 95.217.18.238:15600 / X4wd3my8o6t
panic: send on closed channel

goroutine 15399053 [running]:
github.com/iotaledger/hive.go/websockethub.(*Client).Send(0xc0168ab140, 0x10d1e80, 0xc023cb32e0, 0x0, 0x0, 0x0)
        /github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200810103552-94bbf59c54fa/websockethub/client.go:205 +0x147
github.com/gohornet/hornet/plugins/dashboard.websocketRoute.func2(0xc0168ab140, 0xc0143edb30, 0xc010bc5f05)
        /__w/hornet/hornet/plugins/dashboard/routes.go:169 +0x101
github.com/gohornet/hornet/plugins/dashboard.websocketRoute.func3.2(0xc0168ab140, 0xc014402bc0, 0xc0143edb00, 0x2150cd8, 0xc0143edb30)
        /__w/hornet/hornet/plugins/dashboard/routes.go:223 +0x1f7
created by github.com/gohornet/hornet/plugins/dashboard.websocketRoute.func3
        /__w/hornet/hornet/plugins/dashboard/routes.go:196 +0x10e
```

**Comment by muXxer** [comment]
fixed with #610
