### ISSUE TITLE
Close on closed channel in "ordered daemon"

### ISSUE THREAD

**Issue by muXxer** [iotaledger/hornet#8]
Hit "CTRL+C" once
```
2019/12/12 10:59:19 [ INFO ] Gossip: Closing neighbor connections ... done
panic: close of closed channel
goroutine 32 [running]:
github.com/iotaledger/hive.go/daemon/ordered.(*Daemon).shutdown(0xc00007e0c0)
        /go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20191206213336-9f6cd83f0501/daemon/ordered/daemon.go:214 +0x26e
github.com/iotaledger/hive.go/daemon/ordered.(*Daemon).ShutdownAndWait(...)
        /go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20191206213336-9f6cd83f0501/daemon/ordered/daemon.go:245
github.com/iotaledger/hive.go/daemon/ordered.ShutdownAndWait(...)
        /go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20191206213336-9f6cd83f0501/daemon/ordered/daemon.go:47
github.com/gohornet/hornet/plugins/gracefulshutdown.glob..func1.1(0xc007c50060)
        /__w/hornet/hornet/plugins/gracefulshutdown/plugin.go:50 +0xd1
created by github.com/gohornet/hornet/plugins/gracefulshutdown.glob..func1
        /__w/hornet/hornet/plugins/gracefulshutdown/plugin.go:26 +0xf5```

**Comment by muXxer** [comment]
Fixed in v0.2.3
