### ISSUE TITLE
PANIC bundle not found

### ISSUE THREAD

**Issue by r-c-k** [iotaledger/hornet#96]
**Describe the bug**
After running HORNET for ~2 days it panicked with a „bundle not found“ error.

**To Reproduce**
- Run hornet
- Wait
- Panic

**Expected behavior**
Don’t panic.

**Environment information:**
 - OS: Ubuntu 18.04
 - RAM: 16 GB
 - Cores: 6 Cores
 - Type: VPS
 - 0.2.9

**Additional context**
![BC0564D2-447E-4F8B-8134-02ABBCDB98CA](https://user-images.githubusercontent.com/17240275/71359814-22580900-258e-11ea-80b2-b3d958b68b09.jpeg)

**Comment by uwec** [comment]
**Describe the bug**
Got a very similar panic error "bundle not valid"

**Environment information:**
VPS, 4GB RAM, 2 CPU, Hetzner CX21, Hornet 0.2.10

```Jan 01 13:59:00 hornet4-4gb docker[19377]: EOF
Jan 01 13:59:01 hornet4-4gb docker[19377]: reqQ: 02398, reqQMs: 1295774, processor: 00228, LSMI/LMI: 1295603/1295775, addrsMarked: 6090, bndlsValidated: 99901, txReqs(Tx/Rx): 105928/0, newTxs: 107241, TPS: 2513 (in) / 1482 (new) / 43 (out)
Jan 01 13:59:02 hornet4-4gb docker[19377]: reqQ: 00777, reqQMs: 1295774, processor: 00387, LSMI/LMI: 1295603/1295775, addrsMarked: 6144, bndlsValidated: 100955, txReqs(Tx/Rx): 107153/0, newTxs: 108343, TPS: 2455 (in) / 1076 (new) / 43 (out)
Jan 01 13:59:03 hornet4-4gb docker[19377]: reqQ: 01868, reqQMs: 1295774, processor: 00563, LSMI/LMI: 1295603/1295775, addrsMarked: 6170, bndlsValidated: 102055, txReqs(Tx/Rx): 108362/0, newTxs: 109484, TPS: 2455 (in) / 1076 (new) / 43 (out)
Jan 01 13:59:04 hornet4-4gb docker[19377]: reqQ: 01109, reqQMs: 1295774, processor: 00492, LSMI/LMI: 1295603/1295775, addrsMarked: 6197, bndlsValidated: 103606, txReqs(Tx/Rx): 109970/0, newTxs: 111087, TPS: 2420 (in) / 1168 (new) / 23 (out)
Jan 01 13:59:05 hornet4-4gb docker[19377]: reqQ: 02279, reqQMs: 1295774, processor: 00338, LSMI/LMI: 1295603/1295775, addrsMarked: 6202, bndlsValidated: 105044, txReqs(Tx/Rx): 111191/0, newTxs: 112555, TPS: 3294 (in) / 1605 (new) / 76 (out)
Jan 01 13:59:06 hornet4-4gb docker[19377]: 2020/01/01 13:59:06 [ INFO ] Tangle: Run solidity check for Milestone (1295604)...
Jan 01 13:59:06 hornet4-4gb docker[19377]: 2020/01/01 13:59:06 [ INFO ] Tangle: Solidifier finished (31): passed: true, tx: 51, collect: 9.198712ms, total: 9.603181ms, entryTx: 0Jan 01 13:59:06 hornet4-4gb docker[19377]: 2020/01/01 13:59:06 [ PANIC ] Tangle: confirmMilestone: Tx: QHVLANIVWNW9P9SIOICZKZEORDWUYPXEVDJ99WJCXRRVQERFGUCBHOXWVMCWFAOCKACFOZVUUEKCA9999, Bundle not valid: VAJOHANFEOTRSIPCLG9MIPENDFPLQQUGSBLBHMKZ9XVCUSWIKJOOHSPWJAXVLPTAKMPURYAYD9ONODVOW
Jan 01 13:59:06 hornet4-4gb docker[19377]: panic: [ PANIC ] Tangle: confirmMilestone: Tx: QHVLANIVWNW9P9SIOICZKZEORDWUYPXEVDJ99WJCXRRVQERFGUCBHOXWVMCWFAOCKACFOZVUUEKCA9999, Bundle not valid: VAJOHANFEOTRSIPCLG9MIPENDFPLQQUGSBLBHMKZ9XVCUSWIKJOOHSPWJAXVLPTAKMPURYAYD9ONODVOW
Jan 01 13:59:06 hornet4-4gb docker[19377]: goroutine 1165 [running]:
Jan 01 13:59:06 hornet4-4gb docker[19377]: log.(*Logger).Panicln(0xc00009a190, 0xc0045258a8, 0x2, 0x2)
Jan 01 13:59:06 hornet4-4gb docker[19377]:         /usr/local/go/src/log/log.go:226 +0xaa
Jan 01 13:59:06 hornet4-4gb docker[19377]: github.com/iotaledger/hive.go/logger.(*Logger).Panicf(0xc000030a80, 0xde5993, 0x2e, 0xc004525a20, 0x2, 0x2)
Jan 01 13:59:06 hornet4-4gb docker[19377]:         /go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20191219085244-317ae9a463c7/logger/logger.go:158 +0x2a6
Jan 01 13:59:06 hornet4-4gb docker[19377]: github.com/gohornet/hornet/plugins/tangle.confirmMilestone(0xc00013c4f4, 0xc00354caf0)
Jan 01 13:59:06 hornet4-4gb docker[19377]:         /go/src/github.com/gohornet/hornet/plugins/tangle/confirmation.go:77 +0x6d2
Jan 01 13:59:06 hornet4-4gb docker[19377]: github.com/gohornet/hornet/plugins/tangle.solidifyMilestone(0xc000000000)
Jan 01 13:59:06 hornet4-4gb docker[19377]:         /go/src/github.com/gohornet/hornet/plugins/tangle/solidifier.go:334 +0x5e6
Jan 01 13:59:06 hornet4-4gb docker[19377]: github.com/gohornet/hornet/plugins/tangle.configureTangleProcessor.func3(0xc01149bcc0, 0x1, 0x1, 0xc00ff3bf80)
Jan 01 13:59:06 hornet4-4gb docker[19377]:         /go/src/github.com/gohornet/hornet/plugins/tangle/tangle_processor.go:52 +0x4d
Jan 01 13:59:06 hornet4-4gb docker[19377]: github.com/gohornet/hornet/packages/workerpool.(*WorkerPool).startWorkers.func1(0xc0000322d0)
Jan 01 13:59:06 hornet4-4gb docker[19377]:         /go/src/github.com/gohornet/hornet/packages/workerpool/workerpool.go:159 +0x1ad
Jan 01 13:59:06 hornet4-4gb docker[19377]: created by github.com/gohornet/hornet/packages/workerpool.(*WorkerPool).startWorkers
Jan 01 13:59:06 hornet4-4gb docker[19377]:         /go/src/github.com/gohornet/hornet/packages/workerpool/workerpool.go:135 +0x5e
Jan 01 13:59:06 hornet4-4gb systemd[1]: hornet.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 01 13:59:06 hornet4-4gb systemd[1]: hornet.service: Failed with result 'exit-code'.
Jan 01 13:59:06 hornet4-4gb systemd[1]: hornet.service: Service hold-off time over, scheduling restart.
Jan 01 13:59:06 hornet4-4gb systemd[1]: hornet.service: Scheduled restart job, restart counter is at 1.
Jan 01 13:59:06 hornet4-4gb systemd[1]: Stopped Hornet IOTA.```

**Comment by centercirclesolutions** [comment]
Also Had a similar issue. Same Bundle Different confirmMilestone
Rpi3b+
RAM 1GB SWAP 1GB
Ubuntu ARM64
Hornet 2.1

```
Jan 02 01:59:32 ubuntu hornet_service[5307]: reqQ: 00218, reqQMs: 1296357, processor: 00475, LSMI/LMI: 1295603/1296375, addrsMarked: 5943, bndlsValidated: 85539, txReqs(Tx/Rx): 82420/0, newTxs: 92365, TPS: 174 (in) / 143 (new) / 0 (out)
Jan 02 01:59:33 ubuntu hornet_service[5307]: reqQ: 00258, reqQMs: 1296357, processor: 00437, LSMI/LMI: 1295603/1296375, addrsMarked: 5957, bndlsValidated: 85736, txReqs(Tx/Rx): 82619/0, newTxs: 92575, TPS: 470 (in) / 218 (new) / 0 (out)
Jan 02 01:59:34 ubuntu hornet_service[5307]: reqQ: 00275, reqQMs: 1296357, processor: 00598, LSMI/LMI: 1295603/1296375, addrsMarked: 5960, bndlsValidated: 85754, txReqs(Tx/Rx): 82641/0, newTxs: 92599, TPS: 104 (in) / 24 (new) / 0 (out)
Jan 02 01:59:34 ubuntu hornet_service[5307]: 2020/01/02 01:59:34 [ INFO ] Tangle: Run solidity check for Milestone (1295604)...
Jan 02 01:59:35 ubuntu hornet_service[5307]: 2020/01/02 01:59:35 [ INFO ] Tangle: Solidifier finished (28): passed: true, tx: 51, collect: 30.517366ms, total: 35.974766ms, entryTx: 0
Jan 02 01:59:35 ubuntu hornet_service[5307]: 2020/01/02 01:59:35 [ PANIC ] Tangle: confirmMilestone: Tx: QHVLANIVWNW9P9SIOICZKZEORDWUYPXEVDJ99WJCXRRVQERFGUCBHOXWVMCWFAOCKACFOZVUUEKCA9999, Bundle not valid: VAJOHANFEOTRSIPCLG9MIPENDFPLQQUGSBLBHMKZ9XVCUSWIKJOOHSPWJAXVLPTAKMPURYAYD9ONODVOW
Jan 02 01:59:35 ubuntu hornet_service[5307]: panic: [ PANIC ] Tangle: confirmMilestone: Tx: QHVLANIVWNW9P9SIOICZKZEORDWUYPXEVDJ99WJCXRRVQERFGUCBHOXWVMCWFAOCKACFOZVUUEKCA9999, Bundle not valid: VAJOHANFEOTRSIPCLG9MIPENDFPLQQUGSBLBHMKZ9XVCUSWIKJOOHSPWJAXVLPTAKMPURYAYD9ONODVOW
Jan 02 01:59:35 ubuntu hornet_service[5307]: goroutine 1204 [running]:
Jan 02 01:59:35 ubuntu hornet_service[5307]: log.(*Logger).Panicln(0x4000128000, 0x4003591888, 0x2, 0x2)
Jan 02 01:59:35 ubuntu hornet_service[5307]:         /usr/local/go/src/log/log.go:226 +0x90
Jan 02 01:59:35 ubuntu hornet_service[5307]: github.com/iotaledger/hive.go/logger.(*Logger).Panicf(0x400031a870, 0xd93f69, 0x2e, 0x4003591a08, 0x2, 0x2)
Jan 02 01:59:35 ubuntu hornet_service[5307]:         /go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20191219085244-317ae9a463c7/logger/logger.go:158 +0x240
Jan 02 01:59:35 ubuntu hornet_service[5307]: github.com/gohornet/hornet/plugins/tangle.confirmMilestone(0x400013c4f4, 0x401823eaf0)
Jan 02 01:59:35 ubuntu hornet_service[5307]:         /__w/hornet/hornet/plugins/tangle/confirmation.go:77 +0x520
Jan 02 01:59:35 ubuntu hornet_service[5307]: github.com/gohornet/hornet/plugins/tangle.solidifyMilestone(0x4000000000)
Jan 02 01:59:35 ubuntu hornet_service[5307]:         /__w/hornet/hornet/plugins/tangle/solidifier.go:334 +0x5b8
Jan 02 01:59:35 ubuntu hornet_service[5307]: github.com/gohornet/hornet/plugins/tangle.configureTangleProcessor.func3(0x400ebcad00, 0x1, 0x1, 0x400a957b00)
Jan 02 01:59:35 ubuntu hornet_service[5307]:         /__w/hornet/hornet/plugins/tangle/tangle_processor.go:52 +0x50
Jan 02 01:59:35 ubuntu hornet_service[5307]: github.com/gohornet/hornet/packages/workerpool.(*WorkerPool).startWorkers.func1(0x4000128640)
Jan 02 01:59:35 ubuntu hornet_service[5307]:         /__w/hornet/hornet/packages/workerpool/workerpool.go:159 +0x150
Jan 02 01:59:35 ubuntu hornet_service[5307]: created by github.com/gohornet/hornet/packages/workerpool.(*WorkerPool).startWorkers
Jan 02 01:59:35 ubuntu hornet_service[5307]:         /__w/hornet/hornet/packages/workerpool/workerpool.go:135 +0x5c
Jan 02 01:59:35 ubuntu systemd[1]: hornet.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 02 01:59:35 ubuntu systemd[1]: hornet.service: Failed with result 'exit-code'.

```

**Comment by centercirclesolutions** [comment]
I had my node fail on a different milestone restoring from the 12-26-19 snapshot.

Pi4 Ubuntu Server ARM64 4GB RAM Latest Hornet
Snapshot 12/26/29

Here's the relevant part of the log. A larger part of the log is in the attached file:
```Jan 04 11:26:34 ubuntu hornet_service[4497]: 2020/01/04 11:26:34 [ INFO ] Tangle: Milestone couldn't be solidified! 1297541
Jan 04 11:26:34 ubuntu hornet_service[4497]: 2020/01/04 11:26:34 [ INFO ] Tangle: Run solidity check for Milestone (1297541)...
Jan 04 11:26:35 ubuntu hornet_service[4497]: 2020/01/04 11:26:34 [ INFO ] Tangle: Solidifier finished (5): passed: true, tx: 11, collect: 12.782146ms, total: 13.006069ms, entryTx: 0
Jan 04 11:26:35 ubuntu hornet_service[4497]: 2020/01/04 11:26:35 [ PANIC ] Tangle: confirmMilestone: Tx: NZY9OG9ODKDIYFSTZLBVTRPBYBPECBGSTMGKWEPUNVUUIQRRO9CAXQYJLTJKEYSMVFWOBRCRWTFTZ9999, Bundle not valid: VAJOHANFEOTRSIPCLG9MIPENDFPLQQUGSBLBHMKZ9XVCUSWIKJOOHSPWJAXVLPTAKMPURYAYD9ONODVOW
Jan 04 11:26:35 ubuntu hornet_service[4497]: 2020/01/04 11:26:35 [ INFO ] Tangle: Run solidity check for Milestone (1297541)...
Jan 04 11:26:35 ubuntu hornet_service[4497]: 2020/01/04 11:26:35 [ INFO ] Tangle: Solidifier finished (2): passed: true, tx: 2, collect: 41.259µs, total: 49.055µs, entryTx: 0
Jan 04 11:26:35 ubuntu hornet_service[4497]: panic: [ PANIC ] Tangle: confirmMilestone: Tx: NZY9OG9ODKDIYFSTZLBVTRPBYBPECBGSTMGKWEPUNVUUIQRRO9CAXQYJLTJKEYSMVFWOBRCRWTFTZ9999, Bundle not valid: VAJOHANFEOTRSIPCLG9MIPENDFPLQQUGSBLBHMKZ9XVCUSWIKJOOHSPWJAXVLPTAKMPURYAYD9ONODVOW
Jan 04 11:26:35 ubuntu hornet_service[4497]: goroutine 408018 [running]:
Jan 04 11:26:35 ubuntu hornet_service[4497]: log.(*Logger).Panicln(0x40000cc140, 0x400029d888, 0x2, 0x2)
Jan 04 11:26:35 ubuntu hornet_service[4497]:         /usr/local/go/src/log/log.go:226 +0x90
```
[Hornet_FailLog.txt](https://github.com/gohornet/hornet/files/4021930/Hornet_FailLog.txt)

**Comment by alexsporn** [comment]
Please create a new issue if this happens with the new snapshots from the IF and 0.2.11 or later
