### ISSUE TITLE
MQTT crashes the node

### ISSUE THREAD

**Issue by luca-moser** [iotaledger/hornet#963]
Excerpt from crashing node running `6cc1a26172d4812021daebbcfb5585766c2d14ac`:
```
{"level":"info","timestamp":"2021-03-17T14:40:53.639+0100","logger":"broker","caller":"broker/broker.go:275","msg":"read connect from ","clientID":"api.hornet-0.testnet.chrysalis2.com"}
{"level":"warn","timestamp":"2021-03-17T14:40:53.639+0100","logger":"broker","caller":"broker/broker.go:348","msg":"client exist, close old...","clientID":"api.hornet-0.testnet.chrysalis2.com"}
{"level":"error","timestamp":"2021-03-17T14:40:53.640+0100","logger":"broker","caller":"broker/client.go:174","msg":"read packet error: ","error":"read tcp 172.18.0.3:1883->104.46.114.146:1938: use of closed network connection","ClientID":"api.hornet-0.testnet.chrysalis2.com"}
2021-03-17T14:40:53+01:00       INFO    MQTT    Unsubscribe from topic: milestones/confirmed
2021-03-17T14:40:53+01:00       INFO    MQTT    Unsubscribe from topic: messages
{"level":"info","timestamp":"2021-03-17T14:40:53.701+0100","logger":"broker","caller":"broker/broker.go:275","msg":"read connect from ","clientID":"api.hornet-0.testnet.chrysalis2.com"}
{"level":"warn","timestamp":"2021-03-17T14:40:53.701+0100","logger":"broker","caller":"broker/broker.go:348","msg":"client exist, close old...","clientID":"api.hornet-0.testnet.chrysalis2.com"}
{"level":"error","timestamp":"2021-03-17T14:40:53.702+0100","logger":"broker","caller":"broker/client.go:174","msg":"read packet error: ","error":"read tcp 172.18.0.3:1883->104.46.114.146:1939: use of closed network connection","ClientID":"api.hornet-0.testnet.chrysalis2.com"}
{"level":"error","timestamp":"2021-03-17T14:40:53.736+0100","logger":"broker","caller":"broker/client.go:174","msg":"read packet error: ","error":"EOF","ClientID":"api.hornet-0.testnet.chrysalis2.com"}
req(qu/pe/proc/lat): 00000/00000/00000/0000ms, reqQMs: 0, processor: 00000, CMI/LMI: 120845/120845, MPS (in/new/out): 00036/00025/00027, Tips (non-/semi-lazy): 100/0
req(qu/pe/proc/lat): 00000/00000/00000/0000ms, reqQMs: 0, processor: 00000, CMI/LMI: 120845/120845, MPS (in/new/out): 00059/00041/00047, Tips (non-/semi-lazy): 99/0
req(qu/pe/proc/lat): 00000/00000/00000/0000ms, reqQMs: 0, processor: 00000, CMI/LMI: 120845/120845, MPS (in/new/out): 00027/00023/00029, Tips (non-/semi-lazy): 100/0
req(qu/pe/proc/lat): 00000/00000/00000/0000ms, reqQMs: 0, processor: 00000, CMI/LMI: 120845/120845, MPS (in/new/out): 00048/00037/00041, Tips (non-/semi-lazy): 97/0
req(qu/pe/proc/lat): 00000/00000/00000/0000ms, reqQMs: 0, processor: 00000, CMI/LMI: 120845/120845, MPS (in/new/out): 00023/00018/00021, Tips (non-/semi-lazy): 101/0
2021-03-17T14:40:58+01:00       INFO    Tangle  Valid milestone detected! Index: 120846
2021-03-17T14:40:58+01:00       INFO    Tangle  Run solidity check for Milestone (120846)...
2021-03-17T14:40:58+01:00       INFO    Tangle  Solidifier finished: msgs: 2, collect: 0s, solidity 0s, propagation: 0s, total: 0s
2021-03-17T14:40:58+01:00       INFO    Tangle  Milestone confirmed (120846): txsReferenced: 267, txsValue: 0, txsZeroValue: 267, txsConflicting: 0, collect: 3ms, total: 14ms
2021-03-17T14:40:58+01:00       INFO    Tangle  New confirmed milestone: 120846, 26.80 MPS, 26.70 CMPS, 99.63% conf.rate
req(qu/pe/proc/lat): 00000/00000/00000/0000ms, reqQMs: 0, processor: 00000, CMI/LMI: 120846/120846, MPS (in/new/out): 00023/00018/00021, Tips (non-/semi-lazy): 101/0
req(qu/pe/proc/lat): 00000/00000/00000/0000ms, reqQMs: 0, processor: 00000, CMI/LMI: 120846/120846, MPS (in/new/out): 00038/00027/00027, Tips (non-/semi-lazy): 100/0
req(qu/pe/proc/lat): 00000/00000/00000/0000ms, reqQMs: 0, processor: 00000, CMI/LMI: 120846/120846, MPS (in/new/out): 00038/00027/00027, Tips (non-/semi-lazy): 103/0
2021-03-17T14:41:02+01:00       INFO    P2P-Manager     reconnecting <peer.ID 12*X2TaXA>
2021-03-17T14:41:02+01:00       INFO    P2P-Manager     scheduled reconnect in 30.782475118s to <peer.ID 12*X2TaXA>
2021-03-17T14:41:02+01:00       WARN    P2P-Manager     error reconnect <peer.ID 12*X2TaXA>: dial backoff
req(qu/pe/proc/lat): 00000/00000/00000/0000ms, reqQMs: 0, processor: 00000, CMI/LMI: 120846/120846, MPS (in/new/out): 00058/00037/00043, Tips (non-/semi-lazy): 99/0
{"time":"2021-03-17T14:41:02.476329489+01:00","level":"ERROR","prefix":"echo","file":"plugin.go","line":"183","message":"message not found: 63253fe77cc51f99dfcd762bc28df855b8cbe2b14f9fe2edf3846bd9a415f4ad: not found"}
req(qu/pe/proc/lat): 00000/00000/00000/0000ms, reqQMs: 0, processor: 00000, CMI/LMI: 120846/120846, MPS (in/new/out): 00049/00031/00038, Tips (non-/semi-lazy): 100/0
req(qu/pe/proc/lat): 00000/00000/00000/0000ms, reqQMs: 0, processor: 00000, CMI/LMI: 120846/120846, MPS (in/new/out): 00053/00030/00030, Tips (non-/semi-lazy): 100/0
req(qu/pe/proc/lat): 00000/00000/00000/0000ms, reqQMs: 0, processor: 00000, CMI/LMI: 120846/120846, MPS (in/new/out): 00056/00031/00030, Tips (non-/semi-lazy): 98/0
req(qu/pe/proc/lat): 00000/00000/00000/0000ms, reqQMs: 0, processor: 00000, CMI/LMI: 120846/120846, MPS (in/new/out): 00054/00026/00021, Tips (non-/semi-lazy): 101/0
{"time":"2021-03-17T14:41:06.514066286+01:00","level":"ERROR","prefix":"echo","file":"plugin.go","line":"183","message":"output for transaction not found: 291f1ef0d3f94b66376210a5b1997754afa0bf1997411592401a9d03b01ba50b: not found"}
req(qu/pe/proc/lat): 00000/00000/00000/0000ms, reqQMs: 0, processor: 00000, CMI/LMI: 120846/120846, MPS (in/new/out): 00065/00042/00053, Tips (non-/semi-lazy): 100/0
req(qu/pe/proc/lat): 00000/00000/00000/0000ms, reqQMs: 0, processor: 00000, CMI/LMI: 120846/120846, MPS (in/new/out): 00050/00033/00036, Tips (non-/semi-lazy): 99/0
req(qu/pe/proc/lat): 00000/00000/00000/0000ms, reqQMs: 0, processor: 00000, CMI/LMI: 120846/120846, MPS (in/new/out): 00050/00033/00036, Tips (non-/semi-lazy): 103/0
2021-03-17T14:41:09+01:00       INFO    Tangle  Valid milestone detected! Index: 120847
2021-03-17T14:41:09+01:00       INFO    Tangle  Run solidity check for Milestone (120847)...
2021-03-17T14:41:09+01:00       INFO    Tangle  Solidifier finished: msgs: 0, collect: 0s, solidity 0s, propagation: 0s, total: 0s
2021-03-17T14:41:09+01:00       INFO    Tangle  Milestone confirmed (120847): txsReferenced: 335, txsValue: 0, txsZeroValue: 335, txsConflicting: 0, collect: 10ms, total: 53ms
2021-03-17T14:41:09+01:00       INFO    Tangle  New confirmed milestone: 120847, 35.00 MPS, 33.50 CMPS, 95.71% conf.rate
{"level":"info","timestamp":"2021-03-17T14:41:10.141+0100","logger":"broker","caller":"broker/broker.go:275","msg":"read connect from ","clientID":"api.hornet-0.testnet.chrysalis2.com"}
{"level":"error","timestamp":"2021-03-17T14:41:10.235+0100","logger":"broker","caller":"broker/client.go:174","msg":"read packet error: ","error":"EOF","ClientID":"api.hornet-0.testnet.chrysalis2.com"}
{"level":"info","timestamp":"2021-03-17T14:41:10.332+0100","logger":"broker","caller":"broker/broker.go:275","msg":"read connect from ","clientID":"api.hornet-0.testnet.chrysalis2.com"}
req(qu/pe/proc/lat): 00000/00000/00000/0000ms, reqQMs: 0, processor: 00000, CMI/LMI: 120847/120847, MPS (in/new/out): 00057/00035/00036, Tips (non-/semi-lazy): 101/0
2021-03-17T14:41:10+01:00       INFO    MQTT    Subscribe to topic: milestones/confirmed
2021-03-17T14:41:10+01:00       INFO    MQTT    Subscribe to topic: messages
{"level":"error","timestamp":"2021-03-17T14:41:10.684+0100","logger":"broker","caller":"broker/client.go:174","msg":"read packet error: ","error":"read tcp 172.18.0.3:1883->20.190.228.100:1153: use of closed network connection","ClientID":"api.hornet-0.testnet.chrysalis2.com"}
2021-03-17T14:41:10+01:00       INFO    MQTT    Unsubscribe from topic: milestones/confirmed
2021-03-17T14:41:10+01:00       INFO    MQTT    Unsubscribe from topic: messages
{"level":"info","timestamp":"2021-03-17T14:41:10.780+0100","logger":"broker","caller":"broker/broker.go:275","msg":"read connect from ","clientID":"api.hornet-0.testnet.chrysalis2.com"}
{"level":"error","timestamp":"2021-03-17T14:41:10.887+0100","logger":"broker","caller":"broker/client.go:174","msg":"read packet error: ","error":"EOF","ClientID":"api.hornet-0.testnet.chrysalis2.com"}
{"level":"info","timestamp":"2021-03-17T14:41:10.887+0100","logger":"broker","caller":"broker/broker.go:275","msg":"read connect from ","clientID":"api.hornet-0.testnet.chrysalis2.com"}
2021-03-17T14:41:10+01:00       INFO    MQTT    Subscribe to topic: messages
{"level":"info","timestamp":"2021-03-17T14:41:10.988+0100","logger":"broker","caller":"broker/broker.go:275","msg":"read connect from ","clientID":"api.hornet-0.testnet.chrysalis2.com"}
{"level":"warn","timestamp":"2021-03-17T14:41:10.988+0100","logger":"broker","caller":"broker/broker.go:348","msg":"client exist, close old...","clientID":"api.hornet-0.testnet.chrysalis2.com"}
{"level":"error","timestamp":"2021-03-17T14:41:10.988+0100","logger":"broker","caller":"broker/client.go:174","msg":"read packet error: ","error":"read tcp 172.18.0.3:1883->20.190.228.100:1156: use of closed network connection","ClientID":"api.hornet-0.testnet.chrysalis2.com"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x13e82d7]

goroutine 166999 [running]:
github.com/fhmq/hmq/broker.(*client).Close(0xc001478300)
        /go/pkg/mod/github.com/fhmq/hmq@v0.0.0-20210226074401-7cc3949bbe89/broker/client.go:797 +0x1f7
github.com/fhmq/hmq/broker.(*Broker).handleConnection(0xc0003484b0, 0x0, 0x20ac470, 0xc000115730)
        /go/pkg/mod/github.com/fhmq/hmq@v0.0.0-20210226074401-7cc3949bbe89/broker/broker.go:351 +0x119a
created by github.com/fhmq/hmq/broker.(*Broker).StartClientListening
        /go/pkg/mod/github.com/fhmq/hmq@v0.0.0-20210226074401-7cc3949bbe89/broker/broker.go:220 +0xad1
```

**Comment by muXxer** [comment]
Closed with #966
