### ISSUE TITLE
Node crashes on shutdown in the message processor

### ISSUE THREAD

**Issue by muXxer** [iotaledger/hornet#968]
Because of wrong shutdown order, the node crashes because the message processor object storage was already shut down, but messages are still broadcasted on solidity.

**Comment by muXxer** [comment]
```
Apr 12 11:11:24 spamtest-werner hornet[704752]: panic: trying to access shutdown object storage
Apr 12 11:11:24 spamtest-werner hornet[704752]: goroutine 451 [running]:
Apr 12 11:11:24 spamtest-werner hornet[704752]: github.com/iotaledger/hive.go/objectstorage.(*ObjectStorage).ComputeIfAbsent(0xc000121e00, 0xc0065dbc20, 0x10b, 0x10b, 0xc02c5b7e60, 0x1, 0x1bb80c0)
Apr 12 11:11:24 spamtest-werner hornet[704752]:         /root/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20210407190616-baeca30bf2dd/objectstorage/object_storage.go:155 +0x2ba
Apr 12 11:11:24 spamtest-werner hornet[704752]: github.com/gohornet/hornet/pkg/protocol/gossip.(*MessageProcessor).workUnitFor(0xc0007f13b0, 0xc0065dbc20, 0x10b, 0x10b, 0xc004191a00)
Apr 12 11:11:24 spamtest-werner hornet[704752]:         /opt/hornet/pkg/protocol/gossip/msg_proc.go:220 +0x92
Apr 12 11:11:24 spamtest-werner hornet[704752]: github.com/gohornet/hornet/pkg/protocol/gossip.(*MessageProcessor).Broadcast(0xc0007f13b0, 0xc00b0efd20)
Apr 12 11:11:24 spamtest-werner hornet[704752]:         /opt/hornet/pkg/protocol/gossip/msg_proc.go:408 +0x298
Apr 12 11:11:24 spamtest-werner hornet[704752]: github.com/gohornet/hornet/pkg/tangle.(*Tangle).RunTangleProcessor.func5(0xc00b0efd20)
Apr 12 11:11:24 spamtest-werner hornet[704752]:         /opt/hornet/pkg/tangle/tangle_processor.go:81 +0x38
Apr 12 11:11:24 spamtest-werner hornet[704752]: github.com/gohornet/hornet/pkg/model/storage.MessageMetadataCaller(0x1ba79a0, 0xc0048d41b0, 0xc00b0efbe0, 0x1, 0x1)
Apr 12 11:11:24 spamtest-werner hornet[704752]:         /opt/hornet/pkg/model/storage/messages_storage.go:20 +0xc3
Apr 12 11:11:24 spamtest-werner hornet[704752]: github.com/iotaledger/hive.go/events.(*Event).Trigger(0xc0042458f0, 0xc00b0efbe0, 0x1, 0x1)
Apr 12 11:11:24 spamtest-werner hornet[704752]:         /root/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20210407190616-baeca30bf2dd/events/event.go:32 +0x10b
Apr 12 11:11:24 spamtest-werner hornet[704752]: github.com/gohornet/hornet/pkg/tangle.(*Tangle).markMessageAsSolid(0xc00028ec40, 0xc00b0efbd0)
Apr 12 11:11:24 spamtest-werner hornet[704752]:         /opt/hornet/pkg/tangle/solidifier.go:44 +0x145
Apr 12 11:11:24 spamtest-werner hornet[704752]: github.com/gohornet/hornet/pkg/tangle.(*FutureConeSolidifier).solidifyFutureCone.func1(0xc00b0efbc0, 0xc00b0efb00, 0x0, 0x0)
Apr 12 11:11:24 spamtest-werner hornet[704752]:         /opt/hornet/pkg/tangle/solidifier_future_cone.go:110 +0x25a
Apr 12 11:11:24 spamtest-werner hornet[704752]: github.com/gohornet/hornet/pkg/dag.(*ChildrenTraverser).processStackChildren(0xc003cfd0e0, 0xc02c5b7b60, 0x20)
Apr 12 11:11:24 spamtest-werner hornet[704752]:         /opt/hornet/pkg/dag/children_traverser.go:121 +0x1a7
Apr 12 11:11:24 spamtest-werner hornet[704752]: github.com/gohornet/hornet/pkg/dag.(*ChildrenTraverser).Traverse(0xc003cfd0e0, 0xc00a3bb740, 0x20, 0x20, 0xc02c5b7ad0, 0x0, 0x7fd8aca6e501, 0x0, 0x0, 0x0, ...)
Apr 12 11:11:24 spamtest-werner hornet[704752]:         /opt/hornet/pkg/dag/children_traverser.go:89 +0x245
Apr 12 11:11:24 spamtest-werner hornet[704752]: github.com/gohornet/hornet/pkg/tangle.(*FutureConeSolidifier).solidifyFutureCone(0xc004245f20, 0xc003cfd0e0, 0xc003ccf6c0, 0xc006f37e70, 0x1, 0x1, 0x0, 0x2, 0x2)
Apr 12 11:11:24 spamtest-werner hornet[704752]:         /opt/hornet/pkg/tangle/solidifier_future_cone.go:78 +0x148
Apr 12 11:11:24 spamtest-werner hornet[704752]: github.com/gohornet/hornet/pkg/tangle.(*FutureConeSolidifier).SolidifyMessageAndFutureCone(0xc004245f20, 0xc00b0efb10, 0x0, 0x0, 0x0)
Apr 12 11:11:24 spamtest-werner hornet[704752]:         /opt/hornet/pkg/tangle/solidifier_future_cone.go:54 +0x194
Apr 12 11:11:24 spamtest-werner hornet[704752]: github.com/gohornet/hornet/pkg/tangle.(*Tangle).ConfigureTangleProcessor.func2(0xc00b0efb20, 0x1, 0x1, 0xc00e74f020)
Apr 12 11:11:24 spamtest-werner hornet[704752]:         /opt/hornet/pkg/tangle/tangle_processor.go:27 +0x69
Apr 12 11:11:24 spamtest-werner hornet[704752]: github.com/iotaledger/hive.go/workerpool.(*WorkerPool).startWorkers.func1(0xc004268370)
Apr 12 11:11:24 spamtest-werner hornet[704752]:         /root/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20210407190616-baeca30bf2dd/workerpool/workerpool.go:158 +0x1a3
Apr 12 11:11:24 spamtest-werner hornet[704752]: created by github.com/iotaledger/hive.go/workerpool.(*WorkerPool).startWorkers
Apr 12 11:11:24 spamtest-werner hornet[704752]:         /root/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20210407190616-baeca30bf2dd/workerpool/workerpool.go:134 +0x5f```
