### ISSUE TITLE
MQTT lib, concurrent map iteration and write

### ISSUE THREAD

**Issue by luca-moser** [iotaledger/hornet#980]
This bug nuked hornet-0,1,2 in the testnet over night

Excerpt:
```
concurrent map iteration and map write

goroutine 1229768 [running]:
runtime.throw(0x1939236, 0x26)
	/usr/local/go/src/runtime/panic.go:1117 +0x72 fp=0xc005dcf590 sp=0xc005dcf560 pc=0x4440d2
runtime.mapiternext(0xc005dcf7d8)
	/usr/local/go/src/runtime/map.go:858 +0x54c fp=0xc005dcf610 sp=0xc005dcf590 pc=0x41c42c
runtime.mapiterinit(0x15e8420, 0xc005e84ed0, 0xc005dcf7d8)
	/usr/local/go/src/runtime/map.go:848 +0x1c5 fp=0xc005dcf630 sp=0xc005dcf610 pc=0x41bde5
github.com/fhmq/hmq/broker.(*client).Close(0xc004dcc180)
	/go/pkg/mod/github.com/fhmq/hmq@v0.0.0-20210318020249-ccbe364f9fbe/broker/client.go:796 +0x1c5 fp=0xc005dcf848 sp=0xc005dcf630 pc=0x1347ae5
github.com/fhmq/hmq/broker.(*Broker).handleConnection(0xc0031fc000, 0x0, 0x1fd1f88, 0xc00020e648)
	/go/pkg/mod/github.com/fhmq/hmq@v0.0.0-20210318020249-ccbe364f9fbe/broker/broker.go:351 +0x119a fp=0xc005dcffc0 sp=0xc005dcf848 pc=0x133d5ba
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc005dcffc8 sp=0xc005dcffc0 pc=0x47e541
created by github.com/fhmq/hmq/broker.(*Broker).StartClientListening
	/go/pkg/mod/github.com/fhmq/hmq@v0.0.0-20210318020249-ccbe364f9fbe/broker/broker.go:220 +0xad1

goroutine 1 [semacquire, 2137 minutes]:
sync.runtime_Semacquire(0xc0027c60e8)
	/usr/local/go/src/runtime/sema.go:56 +0x45
sync.(*WaitGroup).Wait(0xc0027c60e0)
	/usr/local/go/src/sync/waitgroup.go:130 +0x65
github.com/iotaledger/hive.go/daemon.(*OrderedDaemon).Run(0xc000216180)
	/go/pkg/mod/github.com/muxxer/hive.go@v0.0.0-20210315124228-1f9351ca6d94/daemon/daemon.go:233 +0x58
github.com/gohornet/hornet/pkg/node.(*Node).Run(0xc0006c5f80)
	/app/pkg/node/node.go:264 +0xb9
github.com/gohornet/hornet/pkg/node.Run(0xc00080ff60, 0x3, 0x3, 0xc00081caa0)
	/app/pkg/node/node.go:63 +0x52
main.main()
	/app/main.go:33 +0x334

goroutine 34 [chan receive, 2137 minutes]:
github.com/iotaledger/hive.go/objectstorage.init.0.func1()
	/go/pkg/mod/github.com/muxxer/hive.go@v0.0.0-20210315124228-1f9351ca6d94/objectstorage/leak_detection.go:180 +0x45
created by github.com/iotaledger/hive.go/objectstorage.init.0
	/go/pkg/mod/github.com/muxxer/hive.go@v0.0.0-20210315124228-1f9351ca6d94/objectstorage/leak_detection.go:178 +0x35

goroutine 35 [select, 2137 minutes]:
github.com/ipfs/go-log/writer.(*MirrorWriter).logRoutine(0xc0002e6db0)
	/go/pkg/mod/github.com/ipfs/go-log@v1.0.4/writer/writer.go:71 +0x106
created by github.com/ipfs/go-log/writer.NewMirrorWriter
	/go/pkg/mod/github.com/ipfs/go-log@v1.0.4/writer/writer.go:36 +0xb9
```

**Comment by luca-moser** [comment]
probably fixed through https://github.com/gohornet/hornet/pull/982
