### ISSUE TITLE
hornet node docker container fails to "docker run" on ubuntu 20.10

### ISSUE THREAD

**Issue by dnns92** [iotaledger/hornet#984]
**Describe the bug**
when running the docker container, the build is succesful, but the run fails with this error message: 

```

SnapshotInfo:
        CooAddr: UDYXTZBE9GZGPM9SSQV9LTZNDLJIZMPUVVXYXFYVBLIEUHLSEWFTKZZLXYRHHWVQV9MNNX9KZC9D9UZWZ
        SnapshotIndex: 3379010 (NNRLVJAHKVDYOSYLHJGAICFIG9DPVPNQETPOFZDTBHNYCBRDCARZJ9VTCMJRAHPSEYXBUNNZZOMSZ9999)
        EntryPointIndex: 3379010
        PruningIndex: 3379010
        Timestamp: 2021-03-21 13:22:59 +0000 UTC
        SpentAddressesEnabled: true
2021-03-22T17:42:55Z    INFO    Node    Loading Plugin: Tangle ... done
2021-03-22T17:42:55Z    INFO    Node    Loading Plugin: Peering ... done
2021-03-22T17:42:55Z    INFO    Node    Loading Plugin: WarpSync ... done
2021-03-22T17:42:55Z    INFO    Node    Loading Plugin: URTS ... done
2021-03-22T17:42:55Z    INFO    Node    Loading Plugin: Metrics ... done
panic: total does not match supply: 2779468306140708 != 2779530283277761

goroutine 1 [running]:
github.com/gohornet/hornet/pkg/model/tangle.GetLedgerStateForLSMIWithoutLocking(0x0, 0x4000170100, 0xf3, 0xf3, 0x31)
        /__w/hornet/hornet/pkg/model/tangle/ledger_db.go:380 +0x2ec
github.com/gohornet/hornet/pkg/model/tangle.GetLedgerStateForLSMI(0x0, 0x0, 0x0, 0x0, 0x0)
        /__w/hornet/hornet/pkg/model/tangle/ledger_db.go:392 +0x88
github.com/gohornet/hornet/plugins/snapshot.configure(0x40000d7300)
        /__w/hornet/hornet/plugins/snapshot/plugin.go:106 +0x9dc
github.com/iotaledger/hive.go/node.pluginCaller(0xf31560, 0x1f6b368, 0x40004e1ad0, 0x1, 0x1)
        /github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20201016154508-2514b782563a/node/events.go:14 +0x68
github.com/iotaledger/hive.go/events.(*Event).Trigger(0x4000283110, 0x40004e1ad0, 0x1, 0x1)
        /github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20201016154508-2514b782563a/events/event.go:32 +0xf0
github.com/iotaledger/hive.go/node.(*Node).configure(0x4000552bd0, 0x40000dad10, 0x15, 0x16)
        /github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20201016154508-2514b782563a/node/node.go:93 +0xd4
github.com/iotaledger/hive.go/node.New(0x400028dee8, 0x1, 0x1, 0x40004cbf20)
        /github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20201016154508-2514b782563a/node/node.go:38 +0x13c
github.com/iotaledger/hive.go/node.Run(0x400028dee8, 0x1, 0x1, 0x40004cbf20)
        /github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20201016154508-2514b782563a/node/node.go:51 +0x38
main.main()
        /__w/hornet/hornet/main.go:67 +0x19c
```

**To Reproduce**
- git clone the repo
- cd docker
- docker build -t hornet:latest --build-arg ARCH=arm64 .
- docker run --rm -v $(pwd)/config.json:/app/config.json:ro -v $(pwd)/latest-export.gz.bin:/app/latest-export.gz.bin:ro -v $(pwd)/mainnetdb:/app/mainnetdb --name hornet --net=host hornet:latest

**Environment information:**
 - OS ubuntu 20.10
 - Machine: raspberry pi 4 4gb ram
 - HORNET v 0.5.6:latest

**Additional context**
Add any other context about the problem here [e.g. HORNET logs, errors, screenshots]

**Comment by muXxer** [comment]
`panic: total does not match supply: 2779468306140708 != 2779530283277761`
This means either your snapshot or your database files are corrupted.
Delete both and start with a clean snapshot.

I would also recommend to use the latest version of the develop branch, since the breaking changes to the IOTA protocol in there will be live soon.
